<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/notice">All Notice</a></li>
        <li><a href="/admin/notice/show-pandingcomment">All Pending Comment</a></li>
        <li><a href="/admin/notice/show-allcomment">All Publish Comment</a></li>
        
    </ul>
</div>
<br /><br />
<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>
<?php if (!empty($this->notice)) { ?>

<div class='class="row content-header"'>
            <h4 class='page-header'>Notices:</h4>
</div>

<div class="span12">

    <div id="article-<?php echo $this->notice['notice_id']; ?>">
        <table class="table table-striped table-bordered">
            <tr>
                <td >Titel:</td>
                <td><?php echo $this->notice['title']; ?></td>
            </tr>
            <tr>
                <td >Description:</td>
                <td><?php echo $this->notice['description']; ?></td>
            </tr>
            <tr>
                <td >Create Date:</td>
                <td><?php echo $this->notice['create_date']; ?></td>
            </tr>
            <tr>
                <td >Create By:</td>
                <td><?php echo $this->notice['create_by']; ?></td>
            </tr>
            <tr>
                <td ">Update Date:</td>
                <td><?php echo $this->notice['update_date']; ?></td>
            </tr>
            <tr>
                <td ">Update By:</td>
                <td><?php echo $this->notice['update_by']; ?></td>
            </tr>

        </table>


            <?php
            if (!empty ($authNamespace->adminData['admin_id'])): ?>
                <p>
                    <a href="/admin/notice/valid/id/<?php echo $this->notice['notice_id'] ?>" <?php echo ($this->notice['is_valid'] == 0) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->notice['is_valid'] == 0) ? "Publish" : "Unpublish" ?></a>
			<a href="/admin/notice/active/id/<?php echo $this->notice['notice_id'] ?>" <?php echo ($this->notice['make_active'] == 1) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->notice['make_active'] == 1) ? "Active" : "UnActive" ?></a>
                    <a href="/admin/notice/edit/id/<?php echo  $this->notice['notice_id'] ?>" class="btn edit">Edit</a>
                    <a href="/admin/notice/delete/id/<?php echo $this->notice['notice_id'] ?>" class="btn btn-danger">Delete</a>
                </p>
                <?php endif ?>

        </div>
    </div>

<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
