<div class="row-fluid">
<table class="table table-striped table-bordered">
    <thead>
            <tr>
                <th class="span1">Serial</th>
                <th class="span1">titleee</th>
                <th class="span2">Descriptionee</th>
                <th class="span2">Valid dayee</th>
                <th class="span2">Create Date</th>
                <th class="span1">Create by</th>
                <th class="span1">Action</th>

              
                
                
            </tr>
     </thead>
    <tbody>

    <?php if (!empty($this->getDetailForComment)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No discussion has been found.</td>
    </tr>
    
        <?php else: $count = 0;
        foreach ($this->display AS $display) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>

            <td><?php echo $display['discussion_id'] ?></td>
            <td><?php echo $display['title'] ?></td>
             <td><?php echo $display['description'] ?></td>
            <td><?php echo $display['comment'] ?></td>
            <td><?php echo $display['create_date'] ?></td>

	    <td class="span1"><a href="/blog/discussions/show/id/<?php echo $display['discussion_id'] ?>" class="btn btn-warning">Show</a></td>

        </tr>

            <?php endforeach; endif ?>
<tr>
      <td>   <a class="btn btn-success" href="/blog/discussions/add">New Discussion</a></td>
        
    </tr>
    </tbody>

</table>
</div>
