
<div class="row-fluid">
 <div class="span8">
 <h7>Discussion : </h7>
<hr/>

    <div style="float:right;">
        <a class="btn btn-success" href="/blog/discussions/add">New Discussion</a>
<br><br>
    </div>
    

<div class="tooltip-demo well1">
    <table class="table table-striped table-bordered">
    <thead>
            <tr>
                <th>Serial</th>
                <th >title</th>
                           
            </tr>
     </thead>
    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No discussion has been found.</td>
    </tr>
    
        <?php else: $count = 0;
        foreach ($this->discussions AS $discussion) : ?>

        <tr>
            <td ><?php echo ++$count ?></td>

            <td ><a href="/blog/discussions/show/id/<?php echo $discussion['discussion_id'] ?>" ><?php echo $discussion['title'] ?></a></td>
            
        </tr>

            <?php endforeach; endif ?>
			
    </tbody>
    

</table>
</div>


</div>
<!--/right contain -->
    
<div class="span4">
<br><br>




&nbsp;&nbsp;<h9> List for discussions </h9>  &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
<hr/>
<?php  
  foreach ($this->discussions AS $discussion) : ?>
 <a href="/blog/discussions/show/id/<?php echo $discussion['discussion_id'] ?>" ><?php echo $discussion['title'] ?></a>
<hr/>  
 <?php endforeach ?>



&nbsp;&nbsp;<h9>Discussions  মন্তব্য &nbsp;&nbsp;</h9> <img src="/public/../img/glyphicons_042_group.png">
<hr/>
<a href="#">&nbsp;&nbsp;সৌম্য'র মুখ বই</a>
<hr/>
<a href="#">&nbsp;&nbsp;সৌম্য'র মুখ </a>
<hr/>



&nbsp;&nbsp;<h9> আমার যত ফেভারিট</h9>  &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
<hr/>
&nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
<hr/>
&nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
<hr/>
&nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
<hr/>
&nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
<hr/>


  </div> 


<!--/end right contain -->
</div>

</div>



























