<?php
$authNamespace = new Zend_Session_Namespace('userInformation');
$data          = $authNamespace->userData['user_id'];
?>
<?php if (!empty($this->discussion)) { ?>

<div class="content-header">
    <h7>Discussions:</h7>
</div>
<hr/>
<div class="span11">

    <div id="article-<?php echo $this->discussion['discussion_id']; ?>">
        <div class="well1">
            <table class="table table-striped table-bordered">
                <tr>
                    <td>Discussion Title:</td>
                    <td><?php echo $this->discussion['title']; ?></td>
                </tr>
                <tr>
                    <td>Description:</td>
                    <td><?php echo $this->discussion['description']; ?></td>
                </tr>


                <tr>
                    <td><a href="/blog/discussion-comments/index/id/<?php echo  $this->discussion['discussion_id'] ?>"
                           class="btn edit">display comment</a></td>
                    <td><a href="/blog/discussion-comments/add/id/<?php echo $this->discussion['discussion_id'] ?>"
                           class="btn edit">Give your comment:</a></td>

                </tr>
                <?php $cdata = $this->discussion['create_by'];
                if ($data == $cdata) {
                    ?>
                    <tr>
                        <td>
                            <a href="/blog/discussions/edit/id/<?php echo  $this->discussion['discussion_id'] ?>"
                               class="btn edit">Edit</a>
                        </td>
                        <td>
                            <a href="/blog/discussions/delete/id/<?php echo $this->discussion['discussion_id'] ?>"
                               class="btn btn-danger">Delete</a>
                        </td>

                    </tr>
                    <?php
                }

                ?>

                <tr>
                    <td>

                    </td>
                    <td>
                        <a href="/blog/discussions/index" class="btn edit">Cancel</a>
                    </td>
                </tr>

            </table>
        </div>

    </div>
</div>

<?php } else { ?>

<div class="span11">
    <h3>No such post to show</h3>
</div>
<?php } ?>
