<?php
$authNamespace = new Zend_Session_Namespace('userInformation');
$data= $authNamespace->userData['user_id'];
?>

<?php if (!empty($this->discussion)) { ?>

<div class="row-fluid">

    <div id="article-<?php echo $this->discussion['discussion_id']; ?>">

        <h2 class='page-header'><?php echo $this->discussion['title']; ?></h2>
        <!--<hr>-->
        
        <div class='meta'>
            <p>
                <?php echo $this->discussion['description']; ?>
            </p>
            
            <h4>Comments:</h4>
            <div class="meta">
               <?php if (!empty($this->getAll)) : ?>
            <p>No comment has been found.</p> 
            <?php else: foreach ($this->comment AS $comment) : ?>
            <hr>
            Comment By: <?php echo $comment['username'] ?>
            <hr>
            <?php echo $comment['comment'] ?>
      <hr>
            <?php endforeach; endif ?>

      <a href="/blog/discussion-comments/add/id/<?php echo $this->discussion['discussion_id'] ?>">মন্তব্য</a>
      <hr>
      <?php $cdata=$this->discussion['create_by'];
                if($data==$cdata)
                {
            ?>
      <a href="/blog/discussions/edit/id/<?php echo  $this->discussion['discussion_id'] ?>">Edit</a>
      <a href="/blog/discussions/delete/id/<?php echo $this->discussion['discussion_id'] ?>">Delete</a>
      <?php
                } 
            ?>
            </div>
            
        </div>


        </div>
    </div>

<?php } else { ?>

<div class="span11">
    <h3>No such post to show</h3>
</div>
<?php } ?>

