<div class="row-fluid">
    <h1>My Trash </h1>


</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">

        <thead>
        <tr>
            <th width="5%">Serial</th>
            <th width="10%">title</th>
            <th width="40%">Description</th>


        </tr>
        </thead>

        <tbody>

        <?php if (empty($this->Discussiontrash)) : ?>

        <tr>
            <td colspan="7" class="report-no-data">No Trash for Discussion.</td>
        </tr>

            <?php else: $count = 0;
            foreach ($this->Discussiontrash AS $TrashDiscussion) : ?>

            <tr>
                <td class="centered"><?php echo ++$count ?></td>
                <td class="centered"><?php echo $TrashDiscussion['title'] ?></td>
                <td class="centered"><?php echo $TrashDiscussion['description'] ?></td>

                <td class="centered">
                    <a class="btn btn-warning"
                       href="/blog/discussions/trash/id/<?php echo $TrashDiscussion['discussion_id'] ?>">Restore</a>
                    <a class="btn danger delete"
                       href="/blog/discussions/delete/id/<?php echo $TrashDiscussion['discussion_id'] ?>">Delete</a>
                </td>
            </tr>
                <?php endforeach; endif ?>

        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


