<?php $authNamespace = new Zend_Session_Namespace('userInformation'); ?>
<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th class="span1">Sl</th>
        <th class="span3">Member</th>


        <th class="span2">Access</th>
        <th class="span2">Action</th>

    </tr>
    </thead>

    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No Notice has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->mygroup AS $mygroup) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>

            <td><?php echo $mygroup['user_id'] ?></td>

            <td class="centered"><?php echo ($mygroup['is_active'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></a></td>
            <td class="span1"><a href="<?php echo $mygroup['my_group_id'] ?>" class="btn btn-success">Show</a></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>


