<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
	    <li><a href="/admin/post-types">Post Types</a></li>
	    <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
    </ul>
</div>
<br /><br />

<div class="row-fluid content-header">
    <h1>Group Type</h1>
    <div class="header-buttons">
        <a class="btn btn-success" href="/admin/blog-group-types/add">New Group Type</a>
    </div>
</div>


<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th class="span1">Srl</th>

        <th class="span6">Group Type</th>

    </tr>
    </thead>

    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No group has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->display AS $display) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>

            <td><?php echo $display['group_type'] ?></td>
            <td class="span1"><a href="/admin/blog-group-types/edit/id/<?php echo $display['blog_group_type_id'] ?>"
                                 class="btn btn-success">Edit</a></td>
            <td class="span1"><a href="/admin/blog-group-types/delete/id/<?php echo $display['blog_group_type_id'] ?>"
                                 class="btn btn-warning">Delete</a></td>


        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>

