<div class="subnav">
    <ul class="nav nav-pills">
	 <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
       
    </ul>
</div>
<br /><br />

<div class="row-fluid content-header">
    <h1>Blog Groups</h1>
    <div class="header-buttons">
        <a class="btn btn-success" href="/admin/blog-groups/add">New Group</a>
    </div>
</div>


<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th>Srl</th>
        <th>Blog group</th>
        <th>Blog group type</th>
        <th>Status</th>
        <th>&nbsp;</th>

    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->display)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No group has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->display AS $display) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
                 <td><?php echo $display['blog_group'] ?></td>
            <td><?php echo $display['group_type'] ?></td>
            <td class="centered"><?php echo ($display['blog_group_is_published'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></a></td>

            <td >

                <a href="/admin/blog-groups/blog-group-publish-status/id/<?php echo $display['blog_group_id'] ?>" <?php echo ($display['blog_group_is_published'] == 0) ? "class='btn btn-success'": "class='btn btn-warning'" ?>><?php echo ($display['blog_group_is_published'] == 0) ? "Publish": "Unpublish" ?></a>
                <a href="/admin/blog-groups/edit/id/<?php echo $display['blog_group_id'] ?>"
                                 class="btn btn-success">Edit</a> &nbsp;&nbsp;
            <a href="/admin/blog-groups/delete/id/<?php echo $display['blog_group_id'] ?>"
                                 class="btn btn-warning">Delete</a>
            <a href="/admin/blog-groups/blog-group-posts/id/<?php echo $display['blog_group_id'] ?>"
                                 class="btn btn-success">Show</a></td>
            </td>



        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>

