<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Recover Password</title>
</head>
<?php $linkToClick = "http://{$_SERVER['HTTP_HOST']}/user/auth/reset-password/code/{$this->activation_code}" ?>
<body>
    <p>Dear <?php echo $this->username ?>,</p>
    <p>Please click the link and reset your password:</p>
    <p><a href="<?php echo $linkToClick ?>"><?php echo $linkToClick ?></a></p>

    <p>Thanks,</p>
    <p>Devnet Support Team.</p>
</body>
</html>