<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Thanks for registering on Nokkhotro Blog</title>
    </head>
    <body>
        <img src="http://www.nokkhotroblog.com/img/subhead-banner.jpg" alt="Nokkhotro Blog user signup registration email link">
        <p>Dear <?php echo $this->name; ?>,
        </p>
        <p>Congratulations for your registration.</p>
        <p>Please click the link to activate your account</p>
       <p><a href="http://www.nokkhotroblog.com/activate/<?php echo $this->user_id; ?>/<?php echo $this->activation_code;?>">Activate Now!!</a></p>
        <p>Thanks</p>
        <p><strong>Nokkhotro Blog Team</strong></p>
        <p></p>
        <hr />
        <i>This email is an activation email because you have signed up to use Nokkhotro Blog. If this email is not belongs to you please inform admin@nokkhotroblog.com
         <br />
         Contact Us: Nokkhtro Blog, Dhaka, Bangladesh. email: admin@nokkhotroblog.com
        </i>
    </body>
</html>
