<?php $authNamespace = new Zend_Session_Namespace('userInformation'); ?>

<div class="row-fluid">
    <h1>My Draft </h1>

   
</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">

        <tbody>

            <tr>
                <td><h4>Draft Type</h4></td>
            </tr>
             <tr> <td><a href="/user/draft/blog-draft">Blog Draft</a></td></tr>
            
            <tr>
                <td><a href="/blog/episodes/display-draft">Episode Draft</a></td>
               
            </tr>
           
            
          
            <tr> 
                <td><a href="/blog/discussions/display-draft">Discussion Draft</a></td>
            </tr>
        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


