 <div class="row-fluid content-header">
<h2>Sticky Post </h2>
</div>   
<br>
<section id="tabs">

          <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab">Currently Sticky</a></li>
            <li><a href="#profile" data-toggle="tab"> Sticky History</a></li>

              
              
            
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th>Srl</th>
        <th>Title</th>
        <th>Category</th>
	<th>Description</th>
        <th >Author</th>
        <th>Create Date</th>
     


    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->sticky)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No Sticky has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->sticky AS $sticky) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td><a href="/admin/sticky/show/id/<?php echo $sticky['blog_id'] ?>"><?php echo $sticky['title'] ?></a></td>
	   <td><?php echo $sticky['category_name'] ?></td>
            <td><?php echo $sticky['description'] ?></td>
	     <td><?php echo $sticky['username'] ?></td>
            <td><?php echo $sticky['create_date'] ?></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
            </div>



            <div class="tab-pane fade" id="profile">
<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th>Srl</th>
        <th>Title</th>
       
	<th>Description</th>
        <th >Author</th>
        <th>Create Date</th>
     


    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->history)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No Sticky has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->history AS $history) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td><a href="/admin/sticky/show/id/<?php echo $history['blog_id'] ?>"><?php echo $history['title'] ?></a></td>
	   
            <td><?php echo $history['description'] ?></td>
	     <td><?php echo $history['username'] ?></td>
            <td><?php echo $history['create_date'] ?></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
            </div>




          </div>

    </section>
