<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/pages/index">All Pending Pages</a></li>
        <li><a href="/admin/pages/show-publish">All Publish Pages</a></li>
         <li><a href="/admin/pages/display-trash">Trash</a></li>
    </ul>
</div>

<div class="row-fluid content-header">
    <h1>Pages</h1>
    <div class="header-buttons">
        <a class="btn btn-success" href="/admin/pages/add/">New Page</a>
    </div>
</div>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Serial</th>
            <th>Page Name</th>
            <th>URL</th>
            
            <th >Create by</th>
            <th >Create Date</th>
            <th >Action</th>


        </tr>
        </thead>
        <tbody>

        <?php if (!empty($this->getAll)) : ?>

        <tr>
            <td class="report-no-data" colspan="5">No page has been found.</td>
        </tr>
            <?php else: $count = 0;
            foreach ($this->display AS $display) : ?>

            <tr>
                <td class="centered"><?php echo ++$count ?></td>

                <td><?php echo $display['page_name'] ?></td>
                <td><a href="#"><?php echo $display['permalink'] ?></a></td>

                <td><?php echo $display['last_moderate_by'] ?></td>
                <td><?php echo $display['last_moderate_date'] ?></td>
                <td><a href="/admin/pages/show/id/<?php echo  $display['page_id'] ?>" class="btn btn-success">Show</a>
                </td>
            </tr>

                <?php endforeach; endif ?>
        </tbody>

    </table>

