

<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/discussions">All Discussion</a></li>
        <li><a href="/admin/discussion-comments">Comments</a></li>
    </ul>
</div>
<br /><br />


<div class="row-fluid">
<table class="table table-striped table-bordered">
    <thead>
            <tr>
                <th >Serial</th>
                <th >title</th>
                <th >Status</th>
                <th>Valid day</th>

                <th >Action</th>

            </tr>
     </thead>
    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No discussion has been found.</td>
    </tr>
        <?php else: $count = 0;
        foreach ($this->display AS $display) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>

            <td><?php echo $display['title'] ?></td>
            <td><?php echo $display['status'] ?></td>
             <td><?php echo $display['valid_day'] ?></td>

         
            <td ><a href="/admin/discussions/show/id/<?php echo $display['discussion_id'] ?>"
                                class="btn btn-success">Show</a></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
</div>
