
<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/discussions">All Discussion</a></li>
        <li><a href="/admin/discussion-comments">Comments</a></li>
    </ul>
</div>
</div>
<br /><br />
<?php if (!empty($this->discussion)) { ?>

<div class="content-header">
            <h4 class='page-header'>Discussions:</h4>
</div>

<div class="row-fluid">
<div class="span12">

    <div id="article-<?php echo $this->discussion['discussion_id']; ?>">
        <table class="table table-striped table-bordered">
            <tr>
                <td>Discution:</td>
                <td><?php echo $this->discussion['title']; ?></td>
            </tr>
            <tr>
                <td>Status:</td>
                <td><?php echo $this->discussion['description']; ?></td>
            </tr>
            <tr>
                <td>Create Date:</td>
                <td><?php echo $this->discussion['valid_day']; ?></td>
            </tr>
            <tr>
                <td>Create By:</td>
                <td><?php echo $this->discussion['create_by']; ?></td>
            </tr>
            <tr>
                <td >Update Date:</td>
                <td><?php echo $this->discussion['create_date']; ?></td>
            </tr>
            <tr>
                <td>Update By:</td>
                <td><?php echo $this->discussion['update_by']; ?></td>
            </tr>
            <tr>
                <td>

                
                <td>
                <a href="/admin/discussions/publish/id/<?php echo $this->discussion['discussion_id'] ?>" <?php echo ($this->discussion['status'] == 'pending') ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->discussion['status'] == 'pending') ? "Published": "Unpublished" ?></a>
               
                    <a href="/admin/discussions/edit/id/<?php echo  $this->discussion['discussion_id'] ?>" class="btn edit">Edit</a>
            

            
                <a href="/admin/discussions/delete/id/<?php echo $this->discussion['discussion_id'] ?>" class="btn btn-danger">Delete</a>

                    <a href="/admin/discussions/index" class="btn edit">Cancel</a>
                </td>
	    </tr>

        </table>

        </div>
    </div>
</div>

<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
