 <div class="row-fluid content-header">
<h2>Trash </h2>
</div> 
<br /><br />
<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>
<?php if(!empty($this->display)) {?>

<div class="span12">

    <div id="article-<?php echo $this->display['comment_id']; ?>">
 	  <h3><?php echo $this->display['title']; ?></h3>
          <hr />
          <p>
              <?php echo $this->display['description']; ?>
          </p>




        <div class='meta'>
            <p>Comments: </p>
                        <?php echo $this->display['comments']; ?>

            <p>
            <?php
                  if (!empty ($authNamespace->adminData['username'])): ?>
                      <p>
                       <a href="/admin/publish/publish/id/<?php echo $this->display['comment_id'] ?>" <?php echo ($this->display['is_published'] == 1) ? "class='btn btn-success'": "class='btn btn-warning'" ?>><?php echo ($this->display['is_published'] == 1) ? "Publish": "Unpublish" ?></a>
                       

                       <a href="/admin/publish/edit/id/<?php echo  $this->display['comment_id'] ?>" class="btn edit">Edit</a>
                       <a href="/admin/comments/delete/id/<?php echo $this->display['comment_id'] ?>" class="btn btn-danger">Delete</a>
<a href="/admin/publish/trash/id/<?php echo $this->display['comment_id'] ?>"<?php echo ($this->display['status'] == 1) ? "class='btn btn-success'": "class='btn btn-warning'" ?>><?php echo ($this->display['status'] == 0) ? "Trash": "Restore"?></a>
                      </p>

            <?php endif ?>
            </p>

        </div>
    </div>
</div>
<?php }else{ ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>

