<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>
<?php if(!empty($this->page)) { ?>


<div class="span12">

    <div id="article-<?php echo $this->page['page_id']; ?>">
        <h2 class='page-header'><a
            href="/admin/blogs/show/id/<?php echo $this->page['page_id']; ?>"><?php echo $this->page['page_name']; ?></a>
        </h2>
  <!--      <p class="author">
            Posted in <?php echo $this->page['category_name'] ?> :: &nbsp; Posted By <cite><?php echo $this->page['last_moderate_by'] ;?></cite> ::
            <abbr class="published">Published &nbsp;<?php echo $this->page['create_date']; ?></>
        </p>-->

        <div class='meta'>
            <p>

                <?php echo $this->page['description']; ?>

            </p>
            <?php
                  if (!empty ($authNamespace->adminData['username'])): ?>
                      <p>
                       <a href="/admin/pages/pending/id/<?php echo $this->page['page_id'] ?>" <?php echo ($this->page['status'] == 'pending') ? "class='btn btn-warning'": "class='btn btn-success'" ?>><?php echo ($this->page['status'] == 'pending') ? "Pending": "Publish" ?></a>
                       <a href="/admin/pages/trash/id/<?php echo $this->page['page_id'] ?>" <?php echo ($this->page['status'] == 'pending') ? "class='btn btn-warning'": "class='btn btn-warning'" ?>><?php echo ($this->page['status'] == 'pending') ? "Trash": "Trash" ?></a>
                       <a href="/admin/pages/edit/id/<?php echo  $this->page['page_id'] ?>" class="btn edit">Edit</a>
                       
                      </p>
            <?php endif ?>

        </div>
    </div>

<?php }else{ ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>