<div class="row-fluid content-header">
    <h1>Users Feedback</h1>

</div>

<table class="table table-striped table-bordered">

    <thead>
    <tr>
        <th class="span1">Serial</th>
        <th class="span1">User Name</th>
        <th class="span2">Email</th>
        <th class="span1">Phonenumber</th>
        <th class="span1">feedback</th>
        <th class="span1">Create Date</th>
        <th class="span1">Action</th>


    </tr>
    </thead>

    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No User has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->Display AS $feedback) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td class="centered"><?php echo $feedback['name']; ?></td>
            <td class="centered"><?php echo $feedback['email']; ?></td>
            <td class="centered"><?php echo $feedback['phonenumber']; ?></td>
            <td class="centered"><?php echo $feedback['feedback']; ?></td>
            <td class="centered"><?php echo $feedback['create_date']; ?></td>
            <td class="centered">

                <a href="/admin/feedback/delete/id/<?php echo $feedback['feedback_id'] ?>"
                   class='btn btn-danger'>Delete</a>
            </td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>


</div>

