<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Pending Blogs</a></li>
        <li><a href="/admin/blogs/publish-item">All Publish Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
        <li><a href="/admin/post-types">Post Types</a></li>
        <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
        <li><a href="/admin/admin-trashs/index">Trash</a></li>
        <li><a href="/admin/blogs/show-sticky">Show Sticky</a></li>
    </ul>
</div>
<br /><br />

<table class="table table-striped table-bordered">

    <thead>
    <tr>
        <th class="span1">Serial</th>
        <th class="span8">Title</th>
        <th class="span2">Category</th>
        <th class="span2">Status</th>
        <th class="span2">Publish</th>
        <th class="span2">Selected</th>
        <th class="span2">Username</th>
        <th class="span4">Posted Date</th>
        <th class="span3">&nbsp;</th>
    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->allPostedBlogs)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No blog has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->allPostedBlogs AS $blog) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td><?php echo $blog['title'] ?></td>
            <td class="centered"><?php echo $blog['category_name']; ?></td>
            <td class="centered"><?php echo ($blog['status'] == 'publish') ? "<a href='#' class='btn btn-success'>publish</a>" : "<a href='#' class='btn btn-warning'>pending</a>"; ?></a></td>
            <td class="centered"><?php echo ($blog['is_published'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></a></td>
            <td class="centered"><?php echo ($blog['is_selected'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></td>
            <td class="centered"><?php echo $blog['username']; ?></td>
            <td class="centered"><?php echo $blog['create_date']; ?></td>
            <td class="centered">
                <a href="/admin/blogs/show/id/<?php echo $blog['blog_id'] ?>" class="btn btn-success">Show</a>
            </td>
        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions) ?>

