<div class="row-fluid">
    <h1>My Blog Trash </h1>


</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">

        <thead>
        <tr>
            <th width="5%">Serial</th>
            <th width="10%">title</th>
            <th width="40%">Description</th>


        </tr>
        </thead>

        <tbody>

        <?php if (empty($this->Blogtrash)) : ?>

        <tr>
            <td colspan="7" class="report-no-data">No Blog has been found.</td>
        </tr>

            <?php else: $count = 0;
            foreach ($this->Blogtrash AS $blogtrash) : ?>

            <tr>
                <td class="centered"><?php echo ++$count ?></td>
                <td class="centered"><?php echo $blogtrash['title'] ?></td>
                <td class="centered"><?php echo $blogtrash['description'] ?></td>

                <td class="centered">
                    <a class="btn btn-warning"
                       href="/user/draft/trash/id/<?php echo $blogtrash['blog_id'] ?>">Restore</a>
                    <a class="btn danger delete"
                       href="/user/draft/delete/id/<?php echo $blogtrash['blog_id'] ?>">Delete</a>
                </td>
            </tr>
                <?php endforeach; endif ?>

        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


