
<?php $authNamespace = new Zend_Session_Namespace('userInformation'); ?>
<?php if(!empty($this->userdetail)) { ?>
<div class="subnav">

</div>


<div class="span7">

    <div id="article-<?php echo $this->userdetail['user_id']; ?>">
	<table class="table table-striped table-bordered">

	<tr><td class="span4">Picture Here</td></tr>
        
 	<tr><td class="span2">Name:</td><td class="span5"><?php echo $this->userdetail['name']; ?></td></tr>
        <tr><td class="span2">User Name:</td><td class="span5"><?php echo $this->userdetail['username']; ?></td></tr>
 	<tr><td class="span2">Email Address:</td><td><?php echo $this->userdetail['email_address']; ?></td></tr>
        <tr><td class="span2">User Status:</td><td class="span5"><?php echo $this->userdetail['user_status']; ?></td></tr>
 	<tr><td class="span2">Create Date:</td><td class="span5"><?php echo $this->userdetail['create_date']; ?></td></tr>
        <tr><td class="span2">Last Login:</td><td class="span5"><?php echo $this->userdetail['last_login']; ?></td></tr>
 	
	
		
	</table>
      <a href="/user/blogs/profileedit/id/<?php echo  $this->userinformation['user_id'] ?>" class="btn edit">Update</a>
    </div>
</div>
<?php }else{ ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>


