<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/notice">All Notice</a></li>
        <li><a href="/admin/notice/show-pandingcomment">All Pending Comment</a></li>
        <li><a href="/admin/notice/show-allcomment">All Publish Comment</a></li>
        
    </ul>
</div>
<br /><br />
<div class="row-fluid">
    <div class="span12">
        <?php if (empty($this->errorMsg)) : echo $this->flashMessenger(); ?>
        <?php else: ?>
        <div class="message errormsg"><p><?php echo $this->errorMsg ?></p></div>
        <?php endif; ?>
        <?php echo $this->noticeEntry; ?>
    </div>
</div>
