
<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Pending Blogs</a></li>
<li><a href="/admin/blogs/publish-item">All Publish Blogs</a></li>
      
	    <!--<li><a href="/admin/post-types">Post Types</a></li>-->
        <li><a href="/admin/comments">Comments</a></li>
         <li><a href="/admin/admin-trashs/index">Trash</a></li>

    </ul>
</div>
<br /><br />

    <table class="table table-striped table-bordered">

        <thead>
            <tr>
                <th >Serial</th>
                <th >Title</th>
                <th >Category</th>
		<th >Status</th>
                <th >Publish</th>
                <th >Selected</th>
                <th >Username</th>
                <th >Posted Datedd</th>
                <th >&nbsp;</th>
            </tr>
        </thead>

        <tbody>

            <?php if (empty($this->allPostedBlogs)) : ?>

            <tr><td class="report-no-data" colspan="5">No blog has been found.</td></tr>

            <?php else: $count = 0; foreach($this->allPostedBlogs AS $blog) : ?>

            <tr>
                <td><?php echo ++$count ?></td>
                <td><?php echo $blog['title'] ?></td>
                <td ><?php echo $blog['category_name']; ?></td>
                <td><?php echo ($blog['status'] == 'publish') ? "<a href='#' class='btn btn-success'>publish</a>" : "<a href='#' class='btn btn-warning'>pending</a>"; ?></a></td>
                <td class="centered"><?php echo ($blog['is_published'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></a></td>
                <td ><?php echo ($blog['is_selected']== 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></td>
                <td><?php echo $blog['username']; ?></td>
                <td><?php echo $blog['create_date']; ?></td>
                <td >
                    <a href="/admin/blogs/show/id/<?php echo $blog['blog_id'] ?>" class="btn btn-success">Show</a>
                </td>
            </tr>

            <?php endforeach; endif ?>

        </tbody>

    </table>
    <?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions) ?>

