<div class="row-fluid">
    <div class="span12">


        <center><h4>Novels</h4></center>


    </div>

</div>
<hr>

<div class="row-fluid">

<div class="tooltip-demo well1">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th >Serial</th>
            <th>Novel Name</th>
            </tr>
        </thead>
        <tbody>

        <?php if (empty($this->novelNames)) : ?>

        <tr>
            <td class="report-no-data" colspan="5">No novel has been found.</td>
        </tr>
            <?php else: $count = 0;
            foreach ($this->novelNames AS $novel) : ?>

            <tr>
                <td ><?php echo ++$count ?></td>

                <td ><a
                    href="/<?php echo $novel['username']; ?>/novel/<?php echo $novel['novel_name_permalink'];?>"><?php echo $novel['novel_name'] ?></a></td>


            </tr>

                <?php endforeach; endif ?>

        </tbody>

    </table>
</div>
</div>
