<?php $authNamespace = new Zend_Session_Namespace('userInformation'); ?>
<ul id="myTab" class="nav nav-tabs">
    <li class="active"><a href="#home" data-toggle="tab">Sequential</a></li>
    <li><a href="#profile" data-toggle="tab">Most Commeted</a></li>
    <li><a href="#dropdown1" data-toggle="tab"> Most Viewed</a></li>

</ul>
          <div id="myTabContent" class="tab-content row-fluid span12">
              <div class="tab-pane fade in active" id="home">
                  <div data-spy="scroll" class="scrollspy-example">

                      <?php foreach ($this->recentBlogs AS $selectedBlog): ?>
                      <div id="article-<?php echo $selectedBlog['blog_id']; ?>">
                          <h2 class='page-header'><a
                              href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>"><?php echo $selectedBlog['title']; ?></a>
                          </h2>

                          <p class="author">
                              <a href="/profile/<?php echo $selectedBlog['username'] ?>"><img src="/<?php echo $selectedBlog['profile_picture'] ?>" width="40px" height="40px"/></a>
                              <a href="/profile/<?php echo $selectedBlog['username'] ?>"><?php echo $selectedBlog['username'];?> </a>::
                              <a href="/category/<?php echo $selectedBlog['blog_category_id'] ?>"><?php echo $selectedBlog['category_name'] ?></a> ::
                              &nbsp;<?php echo $selectedBlog['create_date']; ?>:: &nbsp;
                              মন্তব্য টি :: পঠিত বার

                          </p>
                          <hr>


                          <div class='meta'>

                              <?php $imageTag = new Speed_View_Helper_Image();
                              $img = $imageTag->extract($selectedBlog['description']); ?>





                              <div class="thumbnail span4">
                                  <img src="<?php echo  $img; ?>">
                              </div>




                              <?php $excerpt = new Speed_Utility_TextHelper(); ?>

                              <?php

                              $content = $imageTag->removeImageTag($selectedBlog['description']);


                              ?>

                              <p>
                                  <?php echo $excerpt->word_limiter($content, 50); ?><a
                                  href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>">বিস্তারিত
                                  পড়ুন</a><br><br>

                                 <?php

                                  if (empty ($authNamespace->userData['user_id'])): ?>

                                      <a href="/user/auth/login">মন্তব্য </a>&nbsp;&nbsp;&nbsp;<a href="#">ফেভারিট </a>
                                      &nbsp;&nbsp;&nbsp; <a href="#">Like </a>&nbsp;&nbsp;&nbsp; <a href="#">Share </a>

                                      <?php else: ?>

                                      <a href="/comment/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>">মন্তব্য
                                      </a>&nbsp;&nbsp;&nbsp;<a href="#">ফেভারিট </a>&nbsp;&nbsp;&nbsp; <a
                                          href="#">Like </a>&nbsp;&nbsp;&nbsp; <a href="#">Share </a>
                                      <?php endif ?>

                              <hr/>

                              </p>


                          </div>
                      </div>
                      <?php endforeach ?>

                  </div>
              </div>

              <div class="tab-pane fade" id="profile">
                 
                  <div data-spy="scroll" class="scrollspy-example">
                      <?php foreach ($this->maxCommented AS $selectedBlog): ?>
                      <div id="article-<?php echo $selectedBlog['blog_id']; ?>">
                          <h2 class='page-header'><a
                              href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>"><?php echo $selectedBlog['title']; ?></a>
                          </h2>

                          <p class="author">
                              <a href="/profile/<?php echo $selectedBlog['username'] ?>"><img src="/<?php echo $selectedBlog['profile_picture'] ?>" width="40px" height="40px"/></a>
                              <a href="/profile/<?php echo $selectedBlog['username'] ?>"><?php echo $selectedBlog['username'];?> </a>::
                              <a href="/category/<?php echo $selectedBlog['blog_category_id'] ?>"><?php echo $selectedBlog['category_name'] ?></a> ::
                              &nbsp;<?php echo $selectedBlog['create_date']; ?>:: &nbsp;
                              মন্তব্য টি :: পঠিত বার

                          </p>
<hr>


                          <div class='meta'>
                              <p>
                                  <?php  $excerpt = new Speed_Utility_TextHelper(); ?>
                                  <?php echo $excerpt->word_limiter($selectedBlog['description'], 50); ?><a
                                  href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>">বিস্তারিত
                                  পড়ুন</a>
                             
                              <hr/>


                              </p>


                          </div>
                      </div>
                      <?php endforeach ?>
                  </div>

              </div>

              <div class="tab-pane fade" id="dropdown1">
                  <div data-spy="scroll" class="scrollspy-example">
                      <?php foreach ($this->maxViewed AS $selectedBlog): ?>
                      <div id="article-<?php echo $selectedBlog['blog_id']; ?>">
                          <h2 class='page-header'><a
                              href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>"><?php echo $selectedBlog['title']; ?></a>
                          </h2>

                             <p class="author">
                              <a href="/profile/<?php echo $selectedBlog['username'] ?>"><img src="/<?php echo $selectedBlog['profile_picture'] ?>" width="40px" height="40px"/></a>
                              <a href="/profile/<?php echo $selectedBlog['username'] ?>"><?php echo $selectedBlog['username'];?> </a>::
                              <a href="/category/<?php echo $selectedBlog['blog_category_id'] ?>"><?php echo $selectedBlog['category_name'] ?></a> ::
                              &nbsp;<?php echo $selectedBlog['create_date']; ?>:: &nbsp;
                              মন্তব্য টি :: পঠিত বার

                          </p>
                          <hr>


                          <div class='meta'>
<?php $imageTag = new Speed_View_Helper_Image();
                              $img = $imageTag->extract($selectedBlog['description']); ?>





                              <div class="thumbnail span4">
                                  <img src="<?php echo  $img; ?>">
                              </div>




                              <?php $excerpt = new Speed_Utility_TextHelper(); ?>

                              <?php

                              $content = $imageTag->removeImageTag($selectedBlog['description']);


                              ?>

                              <p>
                                  <?php echo $excerpt->word_limiter($content, 50); ?><a
                                  href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>">বিস্তারিত
                                  পড়ুন</a><br><br>

                                 <?php

                                  if (empty ($authNamespace->userData['user_id'])): ?>

                                      <a href="/user/auth/login">মন্তব্য </a>&nbsp;&nbsp;&nbsp;<a href="#">ফেভারিট </a>
                                      &nbsp;&nbsp;&nbsp; <a href="#">Like </a>&nbsp;&nbsp;&nbsp; <a href="#">Share </a>

                                      <?php else: ?>

                                      <a href="/comment/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>">মন্তব্য
                                      </a>&nbsp;&nbsp;&nbsp;<a href="#">ফেভারিট </a>&nbsp;&nbsp;&nbsp; <a
                                          href="#">Like </a>&nbsp;&nbsp;&nbsp; <a href="#">Share </a>
                                      <?php endif ?>

                              <hr/>

                              </p>


                          </div>
                      </div>
                      <?php endforeach ?>
                  </div>

              </div>



