<div class="row-fluid">
    <h1>My Trash </h1>


</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">


        <tbody>

        <tr>
            <td><a href="/user/blogs/trash-blog">Blog Trash</a></td>

        </tr>

        <tr>
            <td><a href="/blog/episodes/display-trash">Episode Trash</a></td>

        </tr>
        <tr>
            <td><a href="/blog/discussions/trash-discussion">Discussion Trash</a></td>

        </tr>
        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


