<?php $authNamespace = new Zend_Session_Namespace('userInformation'); ?>
<div class="row-fluid">
<div class="span8">
    <section id="tabs">
        <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab">Blogs</a></li>
            <li><a href="#profile" data-toggle="tab">comments</a></li>


        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
            <p><?php foreach ($this->userBlogs AS $recentBlogs): ?>
                <div id="article-<?php echo $recentBlogs['blog_id']; ?>">
                    <h2 class='page-header'><a
                        href="/show/<?php echo $recentBlogs['username'] ?>/<?php echo $recentBlogs['permalink']; ?>"><?php echo $recentBlogs['title']; ?></a>
                    </h2>


                    <p class="author">
                        <a href="/profile/<?php echo $recentBlogs['username'] ?>">
                            <?php

                            if (!empty($recentBlogs['profile_picture'])) {
                                ?>
                                <img src="/<?php echo   $recentBlogs['profile_picture'] ?>" width="40px" height="40px"/>
                                <?php } else { ?>

                                <img src="/img/maleIcon.png" alt="" width="40px" height="40px"/>

                                <?php
                            }
                            ?>
                        </a>
                        <a href="/profile/<?php echo $recentBlogs['username'] ?>">

                            <?php

                            if (!empty($recentBlogs['display_name'])) {
                                echo $recentBlogs['display_name'];
                            }
                            else
                            {
                                if (!empty($recentBlogs['name'])) {
                                    echo $recentBlogs['name'];
                                }
                                else
                                {
                                    echo $recentBlogs['username'];
                                }
                            }
                            ?>
                        </a>::
                        <a href="/category/<?php echo $recentBlogs['blog_category_id'] ?>"><?php echo $recentBlogs['category_name'] ?></a>
                        ::
                        &nbsp;<?php echo $recentBlogs['create_date']; ?>:: &nbsp;
                        মন্তব্য টি :: <?php echo $recentBlogs['viewed'] ?> বার পঠিত

                    </p>
                    <hr>

                    <div class='meta'>
                        <p>
                            <?php  $excerpt = new Speed_Utility_TextHelper(); ?>
                            <?php echo $excerpt->word_limiter($recentBlogs['description'], 50); ?><a
                            href="/show/<?php echo $recentBlogs['username'] ?>/<?php echo $recentBlogs['permalink']; ?>">বিস্তারিত </a>
                        </p>


                        <?php

                        if (empty ($authNamespace->userData['user_id'])): ?>
                            <a href="/user/auth/login">মন্তব্য </a>&nbsp;&nbsp;&nbsp;<a href="#">ফেভারিট </a>
                            &nbsp;&nbsp;&nbsp; <a href="#">Like </a>&nbsp;&nbsp;&nbsp; <a href="#">Share </a>

                            <?php else: ?>

                            <a href="/comment/<?php echo $recentBlogs['username'] ?>/<?php echo $recentBlogs['permalink']; ?>">মন্তব্য
                            </a>&nbsp;&nbsp;&nbsp;<a href="#">ফেভারিট </a>&nbsp;&nbsp;&nbsp; <a
                                href="#">Like </a>&nbsp;&nbsp;&nbsp; <a href="#">Share </a>
                            <?php endif ?>
                        <hr/>
                    </div>
                </div>
                <?php endforeach ?></p>

            </div>
            <div class="tab-pane fade" id="profile">

                <?php   if (!empty($this->comments)) :

                foreach ($this->comments as $comment) :

                    ?>

                    <p class="author">
                        <a href="/profile/<?php echo $comment['username'] ?>">
                            <?php

                            if (!empty($comment['profile_picture'])) {
                                ?>
                                <img src="/<?php echo $comment['profile_picture'] ?>" width="40px" height="40px"/>
                                <?php } else { ?>

                                <img src="/img/maleIcon.png" alt="" width="40px" height="40px"/>

                                <?php
                            }
                            ?>
                        </a>::<a href="/profile/<?php echo $comment['username'] ?>">
                        <?php

                        if (!empty($comment['display_name'])) {
                            echo $comment['display_name'];
                        }
                        else
                        {
                            if (!empty($comment['name'])) {
                                echo $comment['name'];
                            }
                            else
                            {
                                echo $comment['username'];
                            }
                        }
                        ?>
                    </a>::&nbsp;<?php echo $comment['create_date']; ?>

                    </p>
                    <hr>

                    <p><?php  $excerpt = new Speed_Utility_TextHelper(); ?>
                        <?php echo $excerpt->word_limiter($comment['comments'], 50); ?><a
                            href="/show/<?php echo $comment['username'] ?>/<?php echo $comment['permalink']; ?>">বিস্তারিত
                            পড়ুন</a></p>


                    <hr/>
                    <?php endforeach;  endif; ?>

            </div>
        </div>
    </section>


    <!--/right contain -->
</div>
<div class="span4">

    <br>
    &nbsp;&nbsp;
    <h9> আমার যত লিংক</h9>
    &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
    <hr/>
    <a href="#">&nbsp;&nbsp;সৌম্য'র মুখ বই</a>
    <hr/>
    <a href="#">&nbsp;&nbsp;সৌম্য'র মুখ </a>
    <hr/>

    &nbsp;&nbsp;
    <h9> আমার যত ফেভারিট</h9>
    &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
    <hr/>
    &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a
    href="#"><?php echo $this->blogInfo['name'] ?></a>
    <hr/>
    &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a
    href="#"><?php echo $this->blogInfo['name'] ?></a>
    <hr/>
    &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a
    href="#"><?php echo $this->blogInfo['name'] ?></a>
    <hr/>
    &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/> &nbsp;&nbsp;<a
    href="#"><?php echo $this->blogInfo['name'] ?></a>
    <hr/>


    &nbsp;&nbsp;
    <h9> পছন্দের যত পোস্ট</h9>
    &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
    <hr/>

    <?php foreach ($this->userBlogs AS $recentBlogs): ?>
            
                <a href="/show/<?php echo $recentBlogs['username'] ?>/<?php echo $recentBlogs['permalink']; ?>"><?php echo $recentBlogs['title']; ?>
    <hr/>

    <?php endforeach; ?>














    <!--    <div class="row-fluid">-->
    <!--        <div class="span12">-->
    <!--	 <table class="table table-bordered table-striped">-->
    <!--            <thead>-->
    <!--             <tr>-->
    <!--               <th style="width: 150px;">-->
    <!--		Favourate Blog-->
    <!---->
    <!---->
    <!--		</th>-->
    <!--               -->
    <!--             </tr>-->
    <!--            </thead>-->
    <!--	 <tbody>-->
    <!--	   <tr>-->
    <!--            <td>sayeed-->
    <!---->
    <!---->
    <!--            </td>-->
    <!--              -->
    <!--             </tr>-->
    <!--             -->
    <!--	   <tr>-->
    <!--            <td>sayeed-->
    <!---->
    <!---->
    <!--            </td>-->
    <!--              -->
    <!--             </tr>-->
    <!--	   <tr>-->
    <!--            <td>sayeed-->
    <!---->
    <!---->
    <!--            </td>-->
    <!--              -->
    <!--             </tr>-->
    <!--	 </tbody>-->
    <!--          </table>-->
    <!--	-->
    <!--  -->
    <!--	</div>-->
    <!--        </div>-->


    <!--<div class="row-fluid">-->
    <!--        <div class="span12">-->
    <!--	 <table class="table table-bordered table-striped">-->
    <!--            <thead>-->
    <!--             <tr>-->
    <!--               <th style="width: 150px;">-->
    <!--		Favourate Bloger:-->
    <!---->
    <!---->
    <!--		</th>-->
    <!--               -->
    <!--             </tr>-->
    <!--            </thead>-->
    <!--	 <tbody>-->
    <!--	   <tr>-->
    <!--            <td>sayeed<br>-->
    <!--		Tomal<br>-->
    <!--		Zafor-->
    <!---->
    <!---->
    <!--            </td>-->
    <!--              -->
    <!--             </tr>-->
    <!--             -->
    <!---->
    <!--	 </tbody>-->
    <!--          </table>-->
    <!--	-->
    <!--  -->
    <!--	</div>-->
    <!--        </div>-->

</div>


<!--/end right contain -->
</div>
