<?php $authNamespace = new Zend_Session_Namespace('userInformation'); ?>
<div class="row-fluid">
    <div class="span12">


        <center>
            <h3 class="well" style="background-color:white;">আমার প্রোফাইল <h3>
        </center>
    </div>

</div>
<hr/>
<div class="span12">

    <table class="table table-striped">

        <tr>
            <td>নাম:</td>
            <td><?php echo $this->userdetail['name']; ?></td>
        </tr>
        <tr>
            <td> ছদ্ম নাম :</td>
            <td><?php echo $this->userdetail['display_name']; ?></td>
        </tr>
        <tr>
            <td>ইউজারনেম:</td>
            <td><?php echo $this->userdetail['username']; ?></td>
        </tr>
        <tr>
            <td>ই-মেইল ঠিকানা:</td>
            <td><?php echo $this->userdetail['email_address']; ?></td>
        </tr>
        <!-- Update -->
        <tr>
            <td>লিঙ্গ :</td>
            <td><?php echo $this->userdetail['sex']; ?></td>
        </tr>

        <tr>
            <td>ফোন :</td>
            <td><?php echo $this->userdetail['phone']; ?></td>
        </tr>
        <tr>
            <td>পেশা :</td>
            <td><?php echo $this->userdetail['profession']; ?></td>
        </tr>
        <!-- Update -->
        <tr>
            <td>জন্ম তারিখ:</td>
            <td><?php echo $this->userdetail['date_of_birth']; ?></td>
        </tr>

        <tr>
            <td>জীবন-বৃত্তান্ত:</td>
            <td><?php echo $this->userdetail['bio']; ?></td>
        </tr>

        <tr>
            <td>শখ:</td>
            <td><?php echo $this->userdetail['hobby']; ?></td>
        </tr>

        <tr>
            <td>শুরুর দিন:</td>
            <td><?php echo date('F jS Y', strtotime($this->userdetail['create_date'])); ?></td>
        </tr>
        <tr>
            <td>সর্বশেষ প্রবেশ:</td>
            <td><?php echo date('F jS Y', strtotime($this->userdetail['last_login'])); ?></td>
        </tr>
        <!-- Update -->

        <tr>
            <td>শহর:</td>
            <td><?php echo $this->userdetail['district']; ?></td>
        </tr>
        <tr>
            <td>দেশ:</td>
            <td><?php echo $this->userdetail['country']; ?></td>
        </tr>

        <!-- End Update   -->

    </table>
    <br/>
    <?php if (!empty($authNamespace->userData['user_id']) AND ($authNamespace->userData['user_id'] == $this->userdetail['user_id'])) : ?>
    <center><a href="/profile-edit" class="btn btn-primary edit">প্রোফাইল পরিবর্তন করুন</a><center>
    <?php endif; ?>

</div>
