<div class="row-fluid">
    <div class="span8">
        <br>

        <div class="well1">
            <?php foreach ($this->selectedBlogs as $selectedBlog): ?>
            <h3><a
                href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>"><?php echo $selectedBlog['title']; ?></a>
            </h3>
            <p class="author">
                <img src="/<?php echo $selectedBlog['profile_picture']; ?>" width="40px" height="40px"/>
                &nbsp; <?php echo $selectedBlog['username'];?>&nbsp;

                ::&nbsp;Posted By
                <cite><?php echo $selectedBlog['category_name'] ?></cite> ::
                <abbr class="published">Published &nbsp;<?php echo $selectedBlog['create_date']; ?></abbr>
            </p>
            <?php $excerpt = new Speed_Utility_TextHelper(); ?>
            <?php echo $excerpt->word_limiter($selectedBlog['description'], 50); ?><a
                href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>">Read
                More</a>


            <hr style="border:dashed #11eeee; border-width:1px 0 0; height:2px; width:100%;">




            <hr/>
            <?php endforeach; ?>

        </div>
        <!--/right contain -->
    </div>
    <div class="span4">
        <br/>
        <h9> Selected Bloger</h9>
        &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
        <hr/>

        &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/>
        &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
        <hr/>
        &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/>
        &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
        <hr/>
        &nbsp;&nbsp;<img src="/<?php echo $this->blogInfo['profile_picture']; ?>" alt="" width="30px" height="30px"/>
        &nbsp;&nbsp;<a href="#"><?php echo $this->blogInfo['name'] ?></a>
        <hr/>

    </div>


    <!--/end right contain -->
</div>
