   <ul class="nav nav-list">
     <li class="nav-header">Menu</li>

    <li ><a href="/admin/blogs">Blog</a></li>
    <li ><a href="/admin/categories">Blog Category</a></li>
     <li ><a href="/admin/blog-groups">Blog Groups</a></li>
    <li > <a href="/admin/notice">Notice</a></li>
   <li > <a href="/admin/blogs/show-sticky">Sticky</a></li>
    <li ><a href="/admin/users">Users</a></li>
    <li><a href="/admin/roles">Roles</a></li>
    <li ><a href="/admin/admin-users">Admins</a></li>
    <li ><a href="/admin/feedback">Feedback</a></li>
    <li ><a href="/admin/pages">Pages</a></li>
    <li ><a href="/admin/novels">Novels</a></li>
    <li><a href="/admin/discussions">Discussion</a></li>
    <li ><a href="/admin/episods">Episods</a></li>

              <!--<li class="nav-header">Accound Function</li>-->

            </ul>
