   <ul class="nav nav-list">
   <h5>  <li class="nav-header">New Admin System </li>
     <li><a href="/admin/panding/index">Wait for Publish Content</a></li>
     <li><a href="/admin/publish">Moderate </a></li>
     <li><a href="/admin/sticky">Sticky Post</a></li>
     <li><a href="/admin/selected">Selected Post</a></li>
     <li><a href="/admin/blognotice">Notice</a></li>
    <li><a href="/admin/trashs">Trash</a></li>
    <li><a href="/admin/comment-trash">Comment Trash</a></li>
   <!--  <li><a href="/admin/blogs">Wait for Publish Content</a></li>
     
     <li><a href="/admin/blogs">Notice</a></li>
     
     <li><a href="/admin/blogs">Activity Log</a></li>-->

     <li class="nav-header">Old Admin System </li>
    <li ><a href="/admin/blogs">Blog</a></li>
    <li ><a href="/admin/categories">Blog Category</a></li>
     <li ><a href="/admin/blog-groups">Blog Groups</a></li>
    <li > <a href="/admin/notice">Notice</a></li>
   <li > <a href="/admin/blogs/show-sticky">Sticky</a></li>
    <li ><a href="/admin/users">Users</a></li>
    <li><a href="/admin/roles">Roles</a></li>
    <li ><a href="/admin/admin-users">Admins</a></li>
    <li ><a href="/admin/feedback">Feedback</a></li>
    <li ><a href="/admin/pages">Pages</a></li>
    <li ><a href="/admin/novels">Novels</a></li>
    <li><a href="/admin/discussions">Discussion</a></li>
    <li ><a href="/admin/episods">Episods</a></li></h5>

              <!--<li class="nav-header">Accound Function</li>-->

            </ul>
