<ul class="nav">
    <li <?php echo ($this->navBar == 'blogs') ? 'class="active"' : '' ?>><a href="/admin/blogs">Blog</a></li>
    <li <?php echo ($this->navBar == 'notice') ? 'class="active"' : '' ?>><a href="/admin/notice">Notice</a></li>
    <li <?php echo ($this->navBar == 'user') ? 'class="active"' : '' ?>><a href="/admin/users">Users</a></li>
    <li <?php echo ($this->navBar == 'roles') ? 'class="active"' : '' ?>><a href="/admin/roles">Roles</a></li>
    <li <?php echo ($this->navBar == 'admins') ? 'class="active"' : '' ?>><a href="/admin/admin-users">Admins</a></li>
    <li <?php echo ($this->navBar == 'feedback') ? 'class="active"' : '' ?>><a href="/admin/feedback">Feedback</a></li>
    <li <?php echo ($this->navBar == 'pages') ? 'class="active"' : '' ?>><a href="/admin/pages">Pages</a></li>
    <li <?php echo ($this->navBar == 'novels') ? 'class="active"' : '' ?>><a href="/admin/novels">Novels</a></li>
    <li <?php echo ($this->navBar == 'discussions') ? 'class="active"' : '' ?>><a
        href="/admin/discussions">Discussion</a></li>
    <li <?php echo ($this->navBar == 'episods') ? 'class="active"' : '' ?>><a href="/admin/episods">Episods</a></li>


</ul>
