<?php
$authNamespace = new Zend_Session_Namespace('userInformation');
echo $this->doctype()
?>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <?php echo $this->headTitle() ?>
                <?php echo $this->headMeta() ?>
                <?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>

                <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
                <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
                <script src="path/to/avro-1.0-beta.min.js" type="text/javascript" charset="utf-8"></script>
                <![endif]-->
                </head>

                <body>

                    <div class="navbar navbar-fixed-top">
                        <div class="navbar-inner">
                            <div class="container-fluid">
                                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </a>
                                <a class="brand" href="#">Dhaka Time : <?php echo date('F jS,D H:ia'); ?></a>

                                <div class="btn-group pull-right">
                                    <?php if (empty($authNamespace->userData['username'])): ?>
                                        <a href="/signup">Sign up</a>
                                        ||
                                        <a href="/auth/login">Login</a>

                                    <?php else: ?>

                                        Welcome to <a href="/me"><?php echo $authNamespace->userData['username'] ?></a> | <a
                                            href="/auth/logout">Logout</a>
                                        <?php endif ?>
                                </div>
                                <div class="nav-collapse">


                                    <input type="text" data-provide="typeahead">


                                </div>
                                <!--/.nav-collapse -->
                            </div>
                        </div>
                    </div>
                    <div class="container">

                        <?php $flashMessenger = $this->flashMessenger();
                        if (!empty($flashMessenger)): ?>
                            <div style="margin-bottom: 18px">
                            <?php echo $flashMessenger ?>
                            </div>
<?php endif; ?>

                        <div class="row-fluid">
                            <div class="span12">
                                <img src="/public/../img/bootstrap-mdo-sfmoma-02.jpg" alt="" width="1300px" height="100px">
                            </div>
                            <div class="row-fluid">
                                <div class="span12">

                                    <div class="subnav">

<?php echo $this->render('navigation.phtml') ?>
                                    </div>


                                </div>
                            </div>
                        </div>


                        <div class="container-fluid">


                            <div class="row-fluid">
                                <div class="span5">

                                    <!-- Selected post
                                    ================================================== -->
<?php if (!empty($this->selectedBlogs)) { ?>
                                        <section id="carousel vertical">


                                            <div class="span12">
                                                <div class="newsticker-jcarousellite">
                                                    <ul>
                                                        <?php foreach ($this->selectedBlogs as $selectedBlog): ?>
                                                            <?php $imageTag = new Speed_View_Helper_Image();
                                                            $img = $imageTag->extract($selectedBlog['description']);
                                                            ?>
                                                            <li>
                                                                <div class="row-fluid">
                                                                    <div class="thumbnail span4">
                                                                        <img src="<?php echo $img; ?>" >
                                                                    </div>
                                                                    <div class="info span6">

                                                                        <a href="/show/<?php echo $selectedBlog['username'] ?>/<?php echo $selectedBlog['permalink']; ?>"><?php echo $selectedBlog['title']; ?></a>

                                                                        <span class="cat"> <?php $excerpt = new Speed_Utility_TextHelper(); ?>

                                                                            <?php
                                                                            $content = $imageTag->removeImageTag($selectedBlog['description']);
                                                                            ?>
                                                                            <?php echo $excerpt->word_limiter($content, 50); ?></span>

                                                                    </div>
                                                                </div>
                                                                <div class="clear"></div>
                                                            </li>
                                                        <?php endforeach; ?>

                                                    </ul>

                                                </div>
                                            </div>
                                        </section>

                                        <span style="float:right;"><a href="/selected-posts">See All</a></span>
                                    <?php } ?>


                                    <div class="row-fluid">

                                        <div class="span12">


                                            <div class="span5">
                                                <table class="table table-bordered table-striped">
                                                    <thead>
                                                        <tr>
                                                            <th style="width: 150px;">Recent Comments
                                                            </th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>


                                                        <?php foreach ($this->recentComments as $comment): ?>
                                                            <tr>
                                                                <td><?php $excerpt = new Speed_Utility_TextHelper(); ?>
                                                                    <a href="/show/<?php echo $comment['comment_id'] ?>"><?php echo $excerpt->word_limiter($comment['comments'], 5); ?></a></td>
                                                            </tr>
                                                        <?php endforeach; ?>


                                                    </tbody>
                                                </table>

                                                <div class="row-fluid">
                                                    <div class="span12">

                                                        <section id="collapse">


                                                            <div class="accordion" id="accordion2">
                                                                <div class="accordion-group">
                                                                    <div class="accordion-heading">
                                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2"
                                                                           href="#collapseOne">
                                                                            Top Poster

                                                                        </a>
                                                                    </div>
                                                                    <div id="collapseOne" class="accordion-body collapse in">
                                                                        <div class="accordion-inner">

                                                                            <?php foreach ($this->topBloger as $blogger): ?>
                                                                                <p><a
                                                                                        href="/profile/<?php echo $blogger['username'] ?>"><?php echo $blogger['username'] ?></a>
                                                                                </p>
                                                                            <?php endforeach; ?>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="accordion-group">
                                                                    <div class="accordion-heading">
                                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2"
                                                                           href="#collapseTwo">
                                                                            Top Commeter
                                                                        </a>
                                                                    </div>
                                                                    <div id="collapseTwo" class="accordion-body collapse">
                                                                        <div class="accordion-inner">
                                                                            <?php foreach ($this->topCommentPoster as $commenter): ?>
                                                                                <p><a
                                                                                        href="/profile/<?php echo $commenter['username'] ?>"><?php echo $commenter['username'] ?></a>
                                                                                </p>
                                                                            <?php endforeach; ?>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <div class="accordion-group">
                                                                    <div class="accordion-heading">
                                                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2"
                                                                           href="#collapseThree">
                                                                            Top Group

                                                                        </a>
                                                                    </div>
                                                                    <div id="collapseThree" class="accordion-body collapse">
                                                                        <div class="accordion-inner">

                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>
                                                        </section>


                                                    </div>


                                                </div>

                                            </div>

                                            <div class="span7">

                                                <table class="table table-bordered table-striped">
                                                    <thead>
                                                        <tr>
                                                            <th style="width: 150px;">Older post</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>

                                                        <?php foreach ($this->maxViewed as $oldBlog) : ?>
                                                            <tr>
                                                                <td><a href="/show/<?php echo $oldBlog['username'] ?>/<?php echo $oldBlog['permalink']; ?>"><?php echo $oldBlog['title']; ?></a>
                                                                </td>

                                                            </tr>
                                                        <?php endforeach; ?>

                                                        </tr>

                                                    </tbody>
                                                </table>


                                                <div class="row-fluid">
                                                    <div class="span12">
                                                        <table class="table table-bordered table-striped">
                                                            <thead>
                                                                <tr>
                                                                    <th style="width: 150px;">Newly Joined Bloger</th>

                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr>
                                                                    <td> <?php foreach ($this->newBlogger AS $newBlogger): ?>
                                                                            <p><a
                                                                                    href="/profile/<?php echo $newBlogger['username'] ?>"><?php echo $newBlogger['username'] ?></a>
                                                                            </p>
                                                                        <?php endforeach; ?></td>

                                                                </tr>


                                                        </table>
                                                    </div>
                                                </div>

                                            </div>


                                        </div>


                                    </div>
                                </div>
                                <!-- Selected post
                                    ================================================== -->
                                <div class="span7">

                                    <div class="row-fluid">
                                        <div class="span9">

                                            <?php foreach ($this->notices AS $notice): ?>
                                                <div id="article-<?php echo $notice['notice_id']; ?>">
                                                    <div class="well">

                                                        <center> <h4><?php echo $notice['title']; ?></h4></center>

                                                        <spam style="text-align:justify;">&nbsp;&nbsp;&nbsp;<span style="float:right;font-size:10px;"><?php echo date('F jS Y', strtotime($notice['create_date'])); ?></span></<spam>

                                                                <?php $excerpt = new Speed_Utility_TextHelper(); ?>
                                                                <?php echo $excerpt->word_limiter($notice['description'], 30); ?>
                                                                </div>

                                                                </div>
                                                            <?php endforeach ?>

                                                            <?php foreach ($this->stickyPost AS $stickyPost): ?>
                                                                <div id="article-<?php echo $stickyPost['blog_id']; ?>">
                                                                    <div class="well">

                                                                        <center> <h4><?php echo $stickyPost['title']; ?></h4></center>

                                                                        <spam style="text-align:justify;">&nbsp;&nbsp;&nbsp;<span style="float:right;font-size:10px;"><?php echo date('F jS Y', strtotime($notice['create_date'])); ?></span></<spam>

                                                                                
                                    




                              <?php $excerpt = new Speed_Utility_TextHelper(); ?>

                              <?php

                              $content = $imageTag->removeImageTag($selectedBlog['description']);


                              ?>

                              <p> <div class="thumbnail span4">
                                  <img src="<?php echo  $img; ?>">
                              </div>
                                  <?php echo $excerpt->word_limiter($content, 50); ?></p></div>
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            
                                                                            

                                                                                

                                                                               

                                                                                </div>
<?php endforeach ?>


                                                                            </div>
                                                                            <div class="span3">

                                                                                <ul class="nav nav-list">
                                                                                    <li class="nav-header"><a href="#">Groups </a></li>

                                                                                    <li class="nav-header"><a href="/episodes/index">Eposodic Blog's</a></li>

                                                                                    <li class="nav-header"><a href="/novels">Novel</a></li>

                                                                                    <li class="nav-header"><a href="#">Magzine</a></li>

                                                                                    <li class="nav-header"><a href="#">Books</a></li>

                                                                                    <li class="nav-header"><a href="#">Library</a></li>

                                                                                    <li class="nav-header"><a href="#">Discursion</a></li>

                                                                                    <li class="nav-header"><a href="#">Calender</a></li>

                                                                                </ul>


                                                                            </div>
                                                                            </div>

                                                                            <div class="row-fluid">

                                                                                <div class="span12">

                                                                                    <!--Tabs for
                                                                                   ================================================== -->
                                                                                    <section id="tabs">


                                                                                        <div class="span12 columns">


                                                                                            <div>
<?php echo $this->layout()->content ?>
                                                                                            </div>


                                                                                        </div>
                                                                                    </section>


                                                                                </div>
                                                                                <!--/span-->


                                                                            </div>
                                                                            <!--/row-->

                                                                            </div>
                                                                            <!--/span-->
                                                                            </div>
                                                                            <!--/row-->

                                                                            <hr>

                                                                                <footer>
                                                                                    <p><?php echo $this->render('navigation_footer.phtml') ?>
                                                                                    </p>
                                                                                </footer>

                                                                                </div>
                                                                                <!--/.fluid-container-->
                                                                                </div>

                                                                                <div class="alert alert-info">

                                                                                </div>


                                                                                <div class="subnav bottombar">
<?php echo $this->render('navigation_buttom.phtml') ?>
                                                                                </div>

                                                                                </body>
                                                                                </html>


                                                                                <script type="text/javascript">

                                                                                    CKEDITOR.replace('description',
                                                                                    {
                                                                                        filebrowserBrowseUrl:'<?= $this->baseUrl(); ?>/includes/ckfinder/ckfinder.html?Type=Files',
                                                                                        filebrowserImageBrowseUrl:'<?= $this->baseUrl(); ?>/includes/ckfinder/ckfinder.html?Type=Images',
                                                                                        filebrowserFlashBrowseUrl:'<?= $this->baseUrl(); ?>/includes/ckfinder/ckfinder.html?Type=Flash',
                                                                                        filebrowserUploadUrl:'<?= $this->baseUrl(); ?>/includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                                                                                        filebrowserImageUploadUrl:'<?= $this->baseUrl(); ?>/includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
                                                                                        filebrowserFlashUploadUrl:'<?= $this->baseUrl(); ?>/includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
                                                                                    });

                                                                                </script>


                                                                                <script type="text/javascript">
                                                                                    $(function () {
                                                                                        $(".newsticker-jcarousellite").jCarouselLite({
                                                                                            vertical:true,
                                                                                            hoverPause:true,
                                                                                            visible:4,
                                                                                            auto:500,
                                                                                            speed:5000
                                                                                        });
                                                                                    });
                                                                                </script>
