<center><p style="padding-top:5px;"><a href="#">Privacy Policy</a>&copy; All rights reserved by <a
    href="<?php echo $this->baseUrl;?>">Nokkhotro Blog</a></p></center>

<!--Google Analytics Tracking Code (added by Shaharia Azam)-->
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-34878055-1']);
    _gaq.push(['_setDomainName', 'nokkhotroblog.com']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();

</script>
<!--End of Google analytics tracking-->
