<?php
$authNamespace = new Zend_Session_Namespace('userInformation');
echo $this->doctype() ?>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <script type="text/javascript">
 $(document).ready(function(){
   $('a').click(function(){
     _gaq.push(['_trackEvent', 'UserProfile', 'Click', $(this).text()]);
   });
 });
</script>
</head>

<body class="userprofile">

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">নক্ষত্র ব্লগ :<?php 
                            date_default_timezone_set('Asia/Dhaka');
                            //echo date('F jS,D h:ia'); ?> 

<?php $bn_date = new Speed_Utility_DateTimeEnToBn(); ?>
<?php echo $date = $bn_date->ShowDate(false); ?></a>

            <?php if (empty($authNamespace->userData['username'])): ?>
                    <p class="nav pull-right">
                        <a data-toggle="modal" href="#myModal"  class="btn btn-primary" type="button" onClick="_gaq.push(['_trackEvent', 'LoginSignup', 'Click', 'Signup']);">নিবন্ধন করুন</a>
                        <a data-toggle="modal" href="#mylogin"  class="btn btn-primary" type="button" onClick="_gaq.push(['_trackEvent', 'LoginSignup', 'click', 'Login']);">প্রবেশ করুন</a>
                    </p>
		<?php else: ?>
                    <ul class="nav pull-right">
                    <li>
                      <a href="/me"> স্বাগতম <?php echo $authNamespace->userData['username'] ?></a>
                      
                    </li>
                    <li><a href="/auth/logout">লগ আউট</a></li>
                    </ul>
		<?php endif ?>
            <!--/.nav-collapse -->
        </div>
    </div>

    <div class="subnav ">
        <?php echo $this->render('navigation.phtml') ?>
    </div>
</div>

<div class="container">
<?php $flashMessenger = $this->flashMessenger();
                        if (!empty($flashMessenger)): ?>
                            <?php echo $flashMessenger ?>
			<?php endif; ?>

<div class="row-fluid">
    <div class="span12">
        <img src="/public/../img/02.jpg" alt="" width="1300px" height="100px">
    </div>
    <div class="row-fluid">
        <div class="span12">
						
            <h1 class="well">Blog of <a href="/blog/<?php echo $this->userDetail['username']; ?>">
                            <?php 
                
                if(!empty($this->userDetail['display_name']))
                {
                echo $this->userDetail['display_name']; 
 		}
		
                else
		{
                    if(!empty($this->userDetail['name']))
			{
                    echo $this->userDetail['name']; 
                    }
                    else 
                    {
                        echo $this->userDetail['username'];
                        
                        }
                       }
                ?>
            
            
            
            </a><?php if(!empty($this->userDetail['date_of_birth']) && $this->userDetail['date_of_birth']!="0000-00-00"){?>( <?php $year=explode("-",$this->userDetail['date_of_birth']);
            echo $year[0];
            ?> - now)<?php }?><span class="pull-right"><a href="/new/<?php echo $this->userDetail['username']; ?>" class="btn btn-primary">নতুন পোস্ট</a></span></h1>

        </div>
    </div>
</div>


<div class="container-fluid">

<div class="row-fluid">
<!--/Left contain -->
<div class="span3">
    <div class="row-fluid">
        <div class="span12">

            <!-- <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th style="width: 150px; height:150px;">

                                    <img src="/<?php echo $this->userDetail['profile_picture']; ?>" />

                                </th>

                            </tr>
                            </thead>

                        </table>-->
            <div class="thumbnail">
                                <?php 
                
                if(!empty($this->userDetail['profile_picture']))
                {
		?>
                <img src="/<?php echo $this->userDetail['profile_picture']; ?>" alt="" width="190px" height="130px"/>
 		   <?php } else { ?>

		<img src="/img/maleIcon.png" alt="" width="190px" height="170px"/>

		<?php
               }
 		?>

            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">


            <?php if (!empty($this->userDetail['facebook_link'])): ?>
            <br>
            <a href="<?php echo $this->userDetail['facebook_link'];?>">ফেইসবুক
                প্রোফাইল</a> &nbsp;
            <?php endif ?>

            <?php if (!empty($this->userDetail['twitter_link'])): ?>
            <hr/>
            <a href="<?php echo $this->userDetail['twitter_link'];?>"><img src="/public/../img/twitter.png">টুইটার
                প্রোফাইল</a> &nbsp;
            <?php endif ?>

            <?php if (!empty($this->userDetail['gtalk_link'])): ?>
            <hr/>
            <a href="<?php echo $this->userDetail['gtalk_link'];?>"><img src="/public/../img/gtalk.png">গুগল টক</a>
            &nbsp;
            <?php endif ?>

            <?php if (!empty($this->userDetail['linkedin_link'])): ?>
            <hr/>
            <a href="<?php echo $this->userDetail['linkedin_link'];?>"><img src="/public/../img/Linkedin-icon.png">লিংক্ড-ইন</a>
            <?php endif ?>

            <hr>

            <?php if ($authNamespace->userData['username'] == $this->userDetail['username']): ?>
            <a onClick="_gaq.push(['_trackEvent', 'UserProfile', 'Click', 'My Profile']);" href="/me/<?php echo $this->userDetail['username']; ?>">আমার প্রোফাইল</a>
            <hr/>
            <?php endif ?>

            <?php if ($authNamespace->userData['username'] == $this->userDetail['username']): ?>

            <a onClick="_gaq.push(['_trackEvent', 'UserProfile', 'Click', 'New Post']);" href="/new/<?php echo $this->userDetail['username']; ?>">নতুন পোস্ট</a>
            <hr/>
            <?php endif ?>

            <a onClick="_gaq.push(['_trackEvent', 'UserProfile', 'Click', 'My Groups']);" href="/groups/<?php echo $this->userDetail['username']; ?>">গ্রুপ</a>
            <hr/>
            <a href="/blog/discussions/index">আলোচনা</a>

            <hr/>
            <a href="/<?php echo $this->userDetail['username'] ?>/novel-list">উপন্যাস</a>
            <hr/>
            <a href="/blog/<?php echo $this->userDetail['username']; ?>">ব্লগিং</a>
            <hr/>
            <a href="/blog/episodes/my-episord">&nbsp;&nbsp;Episode</a>
            <!--<a href="/episode-list/<?php echo $this->userDetail['username'] ?>">&nbsp;&nbsp;Episods</a>-->
	   <?php if ($authNamespace->userData['username'] == $this->userDetail['username']): ?>
 	  <hr/>
            <a href="/user/photo/index">আমার যত ছবি</a><hr/>
          <?php endif ?>
            
        <?php if ($authNamespace->userData['username'] == $this->userDetail['username']): ?>
            <a href="/user/draft/index">সংরক্ষিত পোস্ট</a><hr/>
       <?php endif ?>
            
        <?php if ($authNamespace->userData['username'] == $this->userDetail['username']): ?>
            <a href="/user/trash/index">মুছে ফেলা পোস্ট</a>
     <?php endif ?>
            <!--                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th style="width: 150px;">
                                <?php if (!empty($this->userDetail['facebook_link'])): ?>
                                    <a href="<?php echo $this->userDetail['facebook_link']; ?>">Facebook</a> /&nbsp;
                                <?php endif ?>

                                <?php if (!empty($this->userDetail['twitter_link'])): ?>
                                    <a href="<?php echo $this->userDetail['twitter_link']; ?>">Twitter</a> /&nbsp;
                                <?php endif ?>

                                <?php if (!empty($this->userDetail['gtalk_link'])): ?>
                                    <a href="<?php echo $this->userDetail['gtalk_link']; ?>">Gtalk</a> /&nbsp;
                                <?php endif ?>

                                <?php if (!empty($this->userDetail['linkedin_link'])): ?>
                                    <a href="<?php echo $this->userDetail['linkedin_link']; ?>">Linkedin</a>
                                <?php endif ?>

                                </th>

                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><a href="/me">My Profile</a></td>

                            </tr>

                            <tr>
                                <td><a href="/new">New Blog</a></td>

                            </tr>

                            <tr>
                                <td><a href="/<?php echo $this->userDetail['username'] ?>/novel-list">My Novels</a></td>

                            </tr>

                            <?php
            if (!empty ($authNamespace->userData['username'])): ?>

                            <?php endif ?>
<!--                            <tr>-->
            <!--                                <td>Draft</td>-->
            <!---->
            <!--                            </tr>-->
            <!--                            <tr>-->
            <!--                                <td>Photos</td>-->
            <!---->
            <!--                            </tr>-->
            <!--                            <tr>-->
            <!--                                <td>Events</td>-->
            <!---->
            <!--                            </tr>-->
            <!--                            <tr>-->
            <!--                                <td>Messege</td>-->
            <!---->
            <!--                            </tr>-->
            <!--                            <tr>-->
            <!--                                <td>Calender</td>-->
            <!---->
            <!--                            </tr>-->
            <!--                          <tr>
                                <td><a href="/blog/<?php echo $this->userDetail['username']; ?>">My Bloging</a></td>

                            </tr>
                            <tr>
                                <td><a href="/groups/<?php echo $this->userDetail['username']; ?>">My Groups</a></td>

                            </tr>
                            <tr>
                                <td> <a href="/blog/discussions/index">Discursion</a></td>

                            </tr>
                            <tr>

                                <td> <a href="/episods/my-episord">Episods</a></td>

                            </tr>

                            </tbody>
                        </table>-->

        </div>
    </div>
    <!--                <div class="row-fluid">-->
    <!--                    <div class="span12">-->
    <!--                        <table class="table table-bordered table-striped">-->
    <!--                            <thead>-->
    <!--                            <tr>-->
    <!--                                <th style="width: 150px;">-->
    <!--                                    Friends-->
    <!---->
    <!--                                </th>-->
    <!---->
    <!--                            </tr>-->
    <!--                            </thead>-->
    <!--                            <tbody>-->
    <!--                            <tr>-->
    <!--                                <td>sayeed<br>-->
    <!--                                    Tomal<br>-->
    <!--                                    Zafor-->
    <!---->
    <!---->
    <!--                                </td>-->
    <!---->
    <!--                            </tr>-->
    <!---->
    <!---->
    <!--                            </tbody>-->
    <!--                        </table>-->
    <!---->
    <!---->
    <!--                    </div>-->
    <!--                </div>-->


</div>

<!--/end Left contain -->

<!--/center contain -->
<div class="span9">


    <div class="row-fluid">
        <div class="span12">


            <?php $flashMessenger = $this->flashMessenger();if (!empty($flashMessenger)): ?>
            <div style="margin-bottom: 18px">
                <?php echo $flashMessenger ?>
            </div>
            <?php endif; ?>

            <div>
                <?php echo $this->layout()->content ?>
            </div>


        </div>


    </div>


</div>
<!--/end center contain -->


</div>

<hr>

<footer>
      
    <p>
<?php echo $this->render('navigation_footer.phtml') ?>
    </p>
</footer>

</div>
<!--/.fluid-container-->
</div>
<br><br>


<div class="subnav bottombar">
    <?php echo $this->render('navigation_buttom.phtml') ?>
</div>

    <!--Google Analytics Tracking Code (added by Shaharia Azam)-->
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34878055-1']);
  _gaq.push(['_setDomainName', 'nokkhotroblog.com']);
  _gaq.push(['_trackPageview']);
   ]);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!--End of Google analytics tracking-->
</body>
</html>


<script type="text/javascript">

    CKEDITOR.replace('description',
        {
            filebrowserBrowseUrl:'<?=$this->baseUrl();?>/includes/ckfinder/ckfinder.html?Type=Files',
            filebrowserImageBrowseUrl:'<?=$this->baseUrl();?>/includes/ckfinder/ckfinder.html?Type=Images',
            filebrowserFlashBrowseUrl:'<?=$this->baseUrl();?>/includes/ckfinder/ckfinder.html?Type=Flash',
            filebrowserUploadUrl:'<?=$this->baseUrl();?>/includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl:'<?=$this->baseUrl();?>/includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl:'<?=$this->baseUrl();?>/includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
        });


</script>
