<hr>

<div class="row-fluid content-header">
    <center>Novels</center>
    <?php
    $authNamespace = new Zend_Session_Namespace('userInformation');
    if (!empty($authNamespace->userData['user_id'])) {
        ?>
        <div class="header-buttons">
            <a class="btn btn-success" href="/novels/name/new">New </a>
        </div>
        <?php } ?>
</div>
<br/>



<div class="row-fluid">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th class="span2">Serial</th>
            <th class="span10">Novel Name</th>
        </tr>
        </thead>
        <tbody>

        <?php if (empty($this->novelNames)) : ?>

        <tr>
            <td class="report-no-data" colspan="5">No novel has been found.</td>
        </tr>
            <?php else: $count = 0;
            foreach ($this->novelNames AS $novel) : ?>
            <tr>
                <td class="centered span2"><?php echo ++$count ?></td>

                <td class="span10"><a
                    href="/<?php echo $novel['username'] ?>/my-novel/<?php echo $novel['novel_name_permalink'];?>"><?php echo $novel['novel_name'] ?></a>
                </td>

            </tr>

                <?php endforeach; endif ?>

        </tbody>

    </table>
</div>
