<div class="row-fluid">
<div class="span12">
<h7>Discussion Comment : </h7>
</div>
</div>
<div class="row-fluid">
<div class="well1">
<table class="table table-striped table-bordered">
    <thead>
            <tr>
                <th>Serial</th>
                <th>title</th>
                <th>Comments</th>
                <th>Valid day</th>
               
              
            </tr>
     </thead>
    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No comment has been found.</td>
    </tr>
    
        <?php else: $count = 0;
        foreach ($this->comment AS $comment) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>

            <td><?php echo $comment['discussion_comment_id'] ?></td>
            <td><?php echo $comment['comment'] ?></td>
             <td><?php echo $comment['create_by'] ?></td>
      


        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
</div>
</div>
