<div>
    <div>


        <center><h4>স্টিকি</h4></center>


    </div>

</div>
<hr>

<div>

    <div>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>ক্রমানুসারে</th>
                <th>স্টিকি নাম</th>
                <th>বিস্তারিত স্টিকি</th>
            </tr>
            </thead>
            <tbody>


            <?php if (empty($this->display)) : ?>

            <tr>
                <td class="report-no-data" colspan="5">No Sticky has been found.</td>
            </tr>
                <?php else: $count = 0;
                foreach ($this->display AS $sticky) : ?>
                <!---update---------------------------------------------------------->
                    <?php $imageTag = new Speed_View_Helper_Image();
                    // $img = $imageTag->extract($sticky['description']);
                    ?>

                    <?php $excerpt = new Speed_Utility_TextHelper(); ?>
                    <?php

                    $content = $imageTag->removeImageTag($sticky['description']);

                    ?>

                <!---End update---------------------------------------------------------->
                <tr>
                    <td><?php echo ++$count ?></td>

                    <td><a
                        href="/blog/stickys/show/id/<?php echo $sticky['blog_id'];?>"><?php echo $sticky['title']; ?> </a>
                    </td>

                    <td><?php echo $excerpt->word_limiter($content, 15); ?></td>

                </tr>

                    <?php endforeach; endif ?>

            </tbody>

        </table>
    </div>
</div>
