<div>
   

</div>
<hr />



    <table class="table table-striped table-bordered">
        
        <tbody>
           

        <?php if (!empty($this->stickydisplay)) : ?>

     
                     <tr>
                
                    <td >
                         &nbsp;&nbsp;
            <img src="/<?php echo $this->stickydisplay['profile_picture'] ?>"  width="40px" height="40px"/> 
            &nbsp;Create By :<?php echo $this->stickydisplay['username']; ?>&nbsp;
            &nbsp;&nbsp; &nbsp; Create Date : &nbsp;<?php echo $this->stickydisplay['create_date']; ?>
            <hr />
                   <h4> <?php echo $this->stickydisplay['title']; ?></h4>
             <hr />
                    
                    <?php echo $this->stickydisplay['description']; ?>
                    </td>

                </tr>
  

        </tbody>
<?php endif ?>
    </table>
