<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>

<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
	    <li><a href="/admin/post-types">Post Types</a></li>
	    <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
    </ul>
</div>
<br /><br />
<div class="row-fluid">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th class="span1">Serial</th>
            <th class="span6">Post</th>
            <th class="span1">Publish</th>
            <th class="span2">Create Date</th>
            <th class="span2">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php if (empty($this->blogGroupPosts)) : ?>

        <tr>
            <td class="report-no-data" colspan="5">No novel has been found.</td>
        </tr>
            <?php else: $count = 0;
            foreach ($this->blogGroupPosts AS $blogGroupPosts) : ?>

            <tr>
                <td class="centered span1"><?php echo ++$count ?></td>

                <td class="span6"><a
                    href="/admin/novels/show/id/<?php echo $blogGroupPosts['blog_group_post_id'];?>"><?php echo $blogGroupPosts['title'] ?></a>
                </td>
                <td class="span1">
                        <?php echo ($blogGroupPosts['blog_group_post_is_published'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></a></td>

                <td class="span2"><?php echo $blogGroupPosts['create_date'];?></td>
                <td class="span2">

                    <a href="/admin/blog-groups/show-group-blog-post/id/<?php echo $blogGroupPosts['blog_group_post_id'] ?>" class="btn btn-success">Show</a>

                </td>

            </tr>

                <?php endforeach; endif ?>

        </tbody>

    </table>
</div>

