
<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
	    <li><a href="/admin/post-types">Post Types</a></li>
	    <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
	    <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
         <li><a href="/admin/admin-trashs/index">Trash</a></li>
    </ul>
</div>
<br /><br />

<div class="row-fluid">
    <h1>My Trash</h1>

   
</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">

       

        <tbody>

            <tr>
                <td><a href="/admin/admin-trashs/trash-blog">Blog Trash</a></td>

            </tr>
            
            <tr>
                <td><a href="/admin/admin-trashs/trash-episode">Episode Trash</a></td>

            </tr>
             <tr>
                <td><a href="/admin/admin-trashs/trash-discussion">Discussion Trash</a></td>

            </tr>
        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


