<div class="row-fluid content-header">
<h2>Trash </h2>
</div>
<br>
<section id="tabs">

          <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab">Blog</a></li>
	    <li ><a href="#comment" data-toggle="tab">Comment</a></li>
            <li><a href="#profile" data-toggle="tab">Epsode</a></li>
            <li><a href="#dropdown" data-toggle="tab">Discussion</a></li>
            <li><a href="#novel" data-toggle="tab">Novel</a></li>
            <li><a href="#book" data-toggle="tab">Books</a></li>
            <li><a href="#group" data-toggle="tab">Group</a></li>
              
              
            
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th>Srl</th>
        <th>Title</th>
        <th>Category</th>
	<th>Description</th>
        <th >Author</th>
        <th>Create Date</th>
     


    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->trash)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No group has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->trash AS $trash) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td><a href="/admin/trashs/show/id/<?php echo $trash['blog_id'] ?>"><?php echo $trash['title'] ?></a></td>
	   <td><?php echo $trash['category_name'] ?></td>
            <td><?php echo $trash['description'] ?></td>
	     <td><?php echo $trash['username'] ?></td>
            <td><?php echo $trash['create_date'] ?></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
            </div>




<div class="tab-pane fade" id="comment">
<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th>Srl</th>
        <th>Comment</th>
        <th>Relative Post</th>
        <th >Author</th>
        <th>Create Date</th>
     


    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->comment)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No group has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->comment AS $comment) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
	     <td><?php echo $comment['comments'] ?></td>
            <td><a href="/admin/blogs/show/id/<?php echo $comment['blog_id'] ?>"><?php echo $comment['title'] ?></a></td>
	     <td><?php echo $comment['username'] ?></td>
            <td><?php echo $comment['create_date'] ?></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
            </div>



            <div class="tab-pane fade" id="profile">
<table class="table table-striped table-bordered">

    <thead>
    <tr>

        <th>Srl</th>
       <th>Episode Name</th>
        <th>Episode Number</th>
        
	<th>Description</th>
        <th >Author</th>
        <th>Create Date</th>
     


    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->episod)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No group has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->episod AS $episod) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td><?php echo $episod['episode_name'] ?></td>
            <td><a href="/admin/trashs/show-episode/id/<?php echo $episod['blog_id'] ?>"><?php echo $episod['episode_number'] ?> </a></td>
	   
            <td><?php echo $episod['description'] ?></td>
	     <td><?php echo $episod['username'] ?></td>
            <td><?php echo $episod['create_date'] ?></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
            </div>




            <div class="tab-pane fade" id="dropdown">

    <table class="table table-striped table-bordered">

        <thead>
            <tr>
                <th width="5%">Serial</th>
                <th width="10%">title</th>
                <th width="40%">Description</th>
                
             
            </tr>
        </thead>

        <tbody>

            <?php if (empty($this->discussion)) : ?>

            <tr><td colspan="7" class="report-no-data">No Trash Blog has been found for you .</td></tr>

            <?php else: $count = 0; foreach($this->discussion AS $discussion) : ?>

            <tr>
                <td class="centered"><?php echo ++$count ?></td>
                <td class="centered"><?php echo $discussion['title'] ?></td>
		<td class="centered"><?php echo $discussion['description'] ?></td>
               
                                 
                <td class="centered">
                     <a class="btn btn-warning" href="/admin/trashs/trash-discussion/id/<?php echo $discussion['discussion_id'] ?>">Restore</a>
                    <a class="btn danger delete" href="/admin/trashs/delete-discussion/id/<?php echo $discussion['discussion_id'] ?>">Delete</a>
                </td>
            </tr>
            <?php endforeach; endif ?>
           
        </tbody>

    </table>
            </div>








            <div class="tab-pane fade" id="novel">
novel
            </div>





            <div class="tab-pane fade" id="book">
book
            </div>




            <div class="tab-pane fade" id="group">

sgdfgdfg


            </div>


          </div>

    </section>
