 <div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/admin-users">All Users</a></li>
    </ul>
</div><br><br>
<div class="row-fluid content-header">
    <h1>Admin Users</h1>
    <div class="header-buttons">
        <a class="btn btn-success" href="/admin/admin-users/add">New admin</a>
    </div>
</div>

<table class="table table-striped table-bordered">

    <thead>
    <tr>
        <th class="span1">Serial</th>
        <th class="span1">User Name</th>
        <th class="span2">Admin Name</th>
        <th class="span2">Email</th>
        <th class="span1">Last Login</th>
        <th class="span1">Create Date</th>
        <th class="span1">Update Date</th>
        <th class="span1">Status</th>
        <th class="span1">Show</th>


    </tr>
    </thead>

    <tbody>

    <?php if (empty($this->display)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No User has been found.</td>
    </tr>

        <?php else: $count = 0;
        foreach ($this->display AS $blog) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
            <td class="centered"><?php echo $blog['username']; ?></td>
            <td class="centered"><?php echo $blog['name']; ?></td>
            <td class="centered"><?php echo $blog['email_address']; ?></td>
            <td class="centered"><?php echo $blog['last_login']; ?></td>
            <td class="centered"><?php echo $blog['create_date']; ?></td>
            <td class="centered"><?php echo $blog['update_date']; ?></td>

            <td class="centered">
                <a href="#" class="btn btn-success"><?php echo $blog['user_status']; ?></a>
            </td>
            <td class="centered">

                <a href="/admin/admin-users/show/id/<?php echo $blog['admin_id'] ?>" class='btn btn-warning'>Show</a>
            </td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>