<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/novels/index">All Novels</a></li>

    </ul>
</div>
<br/><br/>

<div class="row-fluid">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Serial</th>
            <th >Novel Name</th>
            <th>Publish</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>

        <?php if (empty($this->novelNames)) : ?>

        <tr>
            <td class="report-no-data" colspan="5">No novel has been found.</td>
        </tr>
            <?php else: $count = 0;
            foreach ($this->novelNames AS $novel) : ?>

            <tr>
                <td><?php echo ++$count ?></td>

                <td ><a
                    href="/admin/novels/novel-post/id/<?php echo $novel['novel_name_id'];?>"><?php echo $novel['novel_name'] ?></a>
                </td>
                <td >

                        <?php echo ($novel['novel_name_is_published'] == 1) ? "<a href='#' class='btn btn-success'>Yes</a>" : "<a href='#' class='btn btn-warning'>No</a>"; ?></a></td>

                <td >

                    <a href="/admin/novels/novel-name-publish-status/id/<?php echo $novel['novel_name_id'] ?>" <?php echo ($novel['novel_name_is_published'] == 0) ? "class='btn btn-success'": "class='btn btn-warning'" ?>><?php echo ($novel['novel_name_is_published'] == 0) ? "Publish": "Unpublish" ?></a>
                    <a href="/admin/novels/edit-novel-name/id/<?php echo $novel['novel_name_id'] ?>" class="btn btn-success">Edit</a> &nbsp;&nbsp;
                    <a href="/admin/novels/delete-novel-name/id/<?php echo $novel['novel_name_id'] ?>" class="btn btn-danger">Delete</a>
                    <a href="/admin/novels/novel-post/id/<?php echo $novel['novel_name_id'] ?>" class="btn btn-success">Show</a>

                </td>

            </tr>

                <?php endforeach; endif ?>

        </tbody>

    </table>
</div>
