<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
</head>

<body>

<div class="container-fluid" style="margin: 0 auto">

    <div class="row">

        <div class="span8 offset7" style="margin-top:200px">

            <?php $flashMessenger = $this->flashMessenger();if (!empty($flashMessenger)): ?>
                <div class="row" style="margin-bottom: 18px">
                <?php echo $flashMessenger ?>
                </div>
            <?php endif; ?>

            <div id="auth-panel" class="hero-unit" style="background-color:#F5F5DA">

                <form action="<?php echo $this->forgetPasswordForm->getAction() ?>"
                      method="<?php echo $this->forgetPasswordForm->getMethod() ?>">

                    <?php echo $this->forgetPasswordForm->getDisplayGroup('auth') ?>

                    <div style="padding: 10px 0 0 125px">
                        <button type="submit" class="btn primary" style="margin-right: 10px">Submit</button>
                        <a href="/user/auth/login">Login</a>
                    </div>

                </form>

            </div>

        </div>

    </div>

</div>
<!-- #content -->

</body>
</html>