<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
</head>

<body>

<div class="container-fluid" style="margin: 0 auto">

    <div class="row">

        <div class="span8 offset7" style="margin-top:200px">

            <?php if (empty($this->errorMsg)) : ?>
            <?php echo $this->flashMessenger() ?>
            <?php else : ?>
            <div class="alert-message error">
                <a class="close" href="#">&times;</a>

                <p><?php echo $this->errorMsg ?></p>
            </div>
            <?php endif ?>

            <div id="auth-panel" class="hero-unit" style="background-color:#F5F5DA">

                <form action="<?php echo $this->resetPasswordForm->getAction() ?>"
                      method="<?php echo $this->resetPasswordForm->getMethod() ?>">

                    <?php echo $this->resetPasswordForm->getDisplayGroup('auth') ?>

                    <div style="padding: 10px 0 0 125px">
                        <button type="submit" class="btn primary" style="margin-right: 10px">Change Password</button>
                        <a href="/user/auth/login">Login</a>
                    </div>

                </form>

            </div>

        </div>

    </div>

</div>
<!-- #content -->

</body>
</html>