<h2>Trash </h2>

<br><br>	
<?php if (!empty($this->episod)) { ?>

<div class="row-fluid">
            <h4 class='page-header'>Episode:</h4>
</div>

<div class="row-fluid">
<div class="span12">

    <div id="article-<?php echo $this->episod['blog_id']; ?>">
        <table class="table table-striped table-bordered">
            <tr>
                <td>Episode Number:</td>
                <td><?php echo $this->episod['episode_number']; ?></td>
            </tr>
            <tr>
                <td>Create By:</td>
                <td><?php echo $this->episod['create_by']; ?></td>
            </tr>
            <tr>
                <td >Description:</td>
                <td><?php echo $this->episod['description']; ?></td>
            </tr>
            <tr>
                <td>Update Date:</td>
                <td><?php echo $this->episod['create_date']; ?></td>
            </tr>
            <tr>
                <td >Update By:</td>
                <td><?php echo $this->episod['update_by']; ?></td>
            </tr>
            <tr>
                <td>
<a href="/admin/publish/trash-episode/id/<?php echo $this->episod['blog_id'] ?>" class="btn btn-warning">Restore</a>
                </td>
                <td>
                <a href="/admin/trashs/delete-episode/id/<?php echo $this->episod['blog_id'] ?>" class="btn btn-danger">Delete</a>
                
                    <a href="/admin/episods/index" class="btn edit">Cancel</a>
                </td>
	    </tr>

        </table>

        </div>
    </div>
</div>

<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
