<?php
$authNamespace = new Zend_Session_Namespace('userInformation');

?>
<?php if (!empty($authNamespace->userData['user_id'])) : ?>
<div class="row-fluid content-header">
    <div class="header-buttons">
        <a class="btn btn-success"
           href="/<?php echo $this->blogInfo['username'] ?>/my-group-post/<?php echo $this->blogGroupName['blog_group_permalink'] ?>">New </a>
    </div>
</div>
<br/>
<?php endif; ?>

<?php if (!empty($this->blogGroupPosts)) { ?>



    <p>
                    <?php foreach ($this->blogGroupPosts AS $blogGroup): ?>
                    <div class="span12">
                        <h2 class='page-header'><a
                            href="/<?php echo $blogGroup['username'] ?>/my-blog-group/<?php echo $blogGroup['blog_group_permalink'] ?>/<?php echo $blogGroup['blog_group_post_permalink'] ?>"><?php echo $blogGroup['title']; ?></a>
                        </h2>

                        <p class="author">
                            Posted in <?php echo $blogGroup['blog_group'] ?> :: &nbsp; Posted By
                            <cite><?php echo $blogGroup['username'];?></cite> ::
                            <abbr class="published">Published &nbsp;<?php echo $blogGroup['create_date']; ?></abbr>
                        </p>


                        <div class='meta'>
                            <p>
                                <?php  $excerpt = new Speed_Utility_TextHelper(); ?>
                                <?php echo $excerpt->word_limiter($blogGroup['description']); ?>
                            <hr/>
                            <a href="/<?php echo $blogGroup['username'] ?>/my-blog-group/<?php echo $blogGroup['blog_group_permalink'] ?>/<?php echo $blogGroup['blog_group_post_permalink'] ?>">Read
                                More</a>
                            <!--                            --><?php
                            //
                            //                            if (empty ($authNamespace->userData['user_id'])): ?>
                            <!---->
                            <!--                                <a href="/user/auth/login">Comment here</a>-->
                            <!---->
                            <!--                                --><?php //else: ?>
                            <!---->
                            <!--                                <a href="/comment/-->
                                <?php //echo $novel['username'] ?><!--/-->
                                <?php //echo $novel['permalink']; ?><!--">Comment-->
                            <!--                                    here</a>-->
                            <!--                                --><?php //endif ?>



                            </p>



                        </div>
                    </div>
                    <?php endforeach ?>
</p>
<?php
} else {
    echo "<p>No Post Found Here.</p>";
} ?>

<br/>
<h4><a href="/novels">Back</a></h4>



