<?php if (!empty($this->blogGroupPost)) { ?>
<div class="span12">
    <div class="span12"
    ">
    <h2 class='page-header'><a
        href="/<?php echo $this->blogGroupPost['username'] ?>/my-blog-group/<?php echo $this->blogGroupPost['blog_group_permalink'] ?>/<?php echo $this->blogGroupPost['blog_group_post_permalink'] ?>"><?php echo $this->blogGroupPost['title']; ?></a>
    </h2>

    <p class="author">
        Posted in <?php echo $this->blogGroupPost['blog_group'] ?> :: &nbsp; Posted By
        <cite><?php echo $this->blogGroupPost['username'];?></cite> ::
        <abbr class="published">Published &nbsp;<?php echo $this->blogGroupPost['create_date']; ?></abbr>
    </p>


    <div class='meta'>
        <p>

            <?php echo $this->blogGroupPost['description']; ?>

        </p>

    </div>
</div>

<div>
    <?php $authNamespace = new Zend_Session_Namespace('userInformation');
    $userId              = $authNamespace->userData['user_id'];
    if ($userId == $this->blogGroupPost['create_by']) {
        ?>
        <p>
            <a href="/<?php echo $this->blogGroupPost['username'] ?>/edit-group-blog-post/<?php echo $this->blogGroupPost['blog_group_post_permalink'] ?>"
               class="btn btn-success">Edit</a> &nbsp;&nbsp;
            <a href="/<?php echo $this->blogGroupPost['username'] ?>/delete-group-blog-post/<?php echo $this->blogGroupPost['blog_group_post_permalink'] ?>"
               class="btn btn-danger">Delete</a>
        </p>
        <?php } ?>
</div>

</div>
<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
