      	<div class="row-fluid">
        <div class="span12">


     <center>Groups</center>


    </div>

   </div>
 <hr>

<div class='class="row content-header"'>
            <h4 class='page-header'>Groups:</h4>
</div>

<div class="span12">

    <div id="article-<?php echo $this->notice['group_id']; ?>">
        <table class="table table-striped table-bordered">
            <tr>
                <td class="span2">Group Type:</td>
                <td><?php echo $this->notice['group_type']; ?></td>
            </tr>
            <tr>
                <td class="span2">Status:</td>
                <td><?php echo $this->notice['is_active']; ?></td>
            </tr>
            <tr>
                <td class="span2">Create Date:</td>
                <td><?php echo $this->notice['create_date']; ?></td>
            </tr>
            <tr>
                <td class="span2">Create By:</td>
                <td><?php echo $this->notice['create_by']; ?></td>
            </tr>
            <tr>
                <td class="span2">Update Date:</td>
                <td><?php echo $this->notice['update_date']; ?></td>
            </tr>
            <tr>
                <td class="span2">Update By:</td>
                <td><?php echo $this->notice['update_by']; ?></td>
            </tr>

        </table>

                <p>
                    <a href="/admin/bloggroups/publish/id/<?php echo $this->notice['group_id'] ?>" <?php echo ($this->notice['is_active'] == 0) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->notice['is_active'] == 0) ? "Publish" : "Unpublish" ?></a>

                    <a href="/admin/bloggroups/edit/id/<?php echo  $this->notice['group_id'] ?>" class="btn edit">Edit</a>
                    <a href="/admin/bloggroups/delete/id/<?php echo $this->notice['group_id'] ?>" class="btn btn-danger">Delete</a>
                </p>

        </div>
    </div>

