 <div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/episods">All Episode</a></li>
        <li><a href="/admin/episods/show-pendingcomments">All Pending Comments</a></li>
        <li><a href="/admin/episods/show-publishcomments">All Publish Comments</a></li>
        
    </ul>
</div><br><br>	
<div class="row-fluid">
<h2>Episode</h2>
<table class="table table-striped table-bordered">
    <thead>
            <tr>
                <th>Serial</th>
                <th>Episode Id</th>
                <th>Episode Number</th>
                <th>Description</th>
                <th>Create Date</th>
            
                <th>Action</th>

              
                
                
            </tr>
     </thead>
    <tbody>

    <?php if (!empty($this->getAll)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No episode has been found.</td>
    </tr>
        <?php else: $count = 0;
        foreach ($this->display AS $display) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>

            <td><?php echo $display['episode_name'] ?></td>                         
            <td><?php echo $display['episode_number'] ?></td>         
             <td><?php echo $display['description'] ?></td>
            <td><?php echo $display['create_date'] ?></td>
            
         
            <td ><a href="/admin/episods/show/id/<?php echo $display['blog_id'] ?>"
                                 class="btn btn-success">Show</a></td>

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
</div>
