<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/episods">All Episodes</a></li>
        <li><a href="/admin/episods/show-pendingcomments">All Pending Comments</a></li>
        <li><a href="/admin/episods/show-publishcomments">All Publish Comments</a></li>
    </ul>
</div>
<br /><br />


<div class="row-fluid">
<h2>Publish Comments</h2>
<table class="table table-striped table-bordered">
    <thead>
            <tr>
                <th>Serial No</th>
                <th>Comments</th>
                <th>Create Date</th>
                <th>Publish</th>
         <!--       <th>Action</th>     -->

              
                
                
            </tr>
     </thead>
    <tbody>

    <?php if (empty($this->displaycomment)) : ?>

    <tr>
        <td class="report-no-data" colspan="5">No published comment has been found.</td>
    </tr>
        <?php else: $count = 0;
        foreach ($this->displaycomment AS $displayComment) : ?>

        <tr>
            <td class="centered"><?php echo ++$count ?></td>
             <td><?php echo $displayComment['comment'] ?></td>
            <td><?php echo $displayComment['create_date'] ?></td>
            
            <td><a href="/admin/episods/publish-comment/id/<?php echo $displayComment['episode_comment_id'] ?>" <?php echo ($displayComment['status'] == 'pending') ? "class='btn btn-success'" : "class='btn btn-warning'"?>><?php echo ($displayComment['status'] == 'pending') ? "Publish": "Pending" ?></a></td>
    <!--        <td ><a href="/admin/episods/show-comment/id/<?php echo $displayComment['blog_id'] ?>"
                                 class="btn btn-success">Show</a></td> -->

        </tr>

            <?php endforeach; endif ?>

    </tbody>

</table>
</div>
