<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>
<?php if (!empty($this->notice)) { ?>
<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
        <li><a href="/admin/post-types">Post Types</a></li>
        <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
    </ul>
</div>
<br/><br/>
<div class='class="row content-header"'>
    <h4 class='page-header'>Groups:</h4>
</div>

<div class="span12">

    <div id="article-<?php echo $this->notice['group_id']; ?>">
        <table class="table table-striped table-bordered">
            <tr>
                <td class="span2">Group Type:</td>
                <td><?php echo $this->notice['group_type']; ?></td>
            </tr>
            <tr>
                <td class="span2">Status:</td>
                <td><?php echo $this->notice['is_active']; ?></td>
            </tr>
            <tr>
                <td class="span2">Create Date:</td>
                <td><?php echo $this->notice['create_date']; ?></td>
            </tr>
            <tr>
                <td class="span2">Create By:</td>
                <td><?php echo $this->notice['create_by']; ?></td>
            </tr>
            <tr>
                <td class="span2">Update Date:</td>
                <td><?php echo $this->notice['update_date']; ?></td>
            </tr>
            <tr>
                <td class="span2">Update By:</td>
                <td><?php echo $this->notice['update_by']; ?></td>
            </tr>

        </table>


        <?php
        if (!empty ($authNamespace->adminData['admin_id'])): ?>
            <p>
                <a href="/admin/bloggroups/publish/id/<?php echo $this->notice['group_id'] ?>" <?php echo ($this->notice['is_active'] == 0) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->notice['is_active'] == 0) ? "Publish" : "Unpublish" ?></a>

                <a href="/admin/bloggroups/edit/id/<?php echo  $this->notice['group_id'] ?>" class="btn edit">Edit</a>
                <a href="/admin/bloggroups/delete/id/<?php echo $this->notice['group_id'] ?>" class="btn btn-danger">Delete</a>
            </p>
            <?php endif ?>

    </div>
</div>

<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
