<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/novels/index">All Novels</a></li>
     </ul>
</div>
<br/><br/>
<?php if(!empty($this->blogGroupPost)) { ?>
<div class="span12">
       <div class="span12" ">
        <h2 class='page-header'><a
            href="/admin/blog-groups/show-group-blog-post/id/<?php echo $this->blogGroupPost['blog_group_post_id'] ?>"><?php echo $this->blogGroupPost['title']; ?></a>
        </h2>

        <p class="author">
            Posted in <?php echo $this->blogGroupPost['blog_group'] ?> :: &nbsp; Posted By <cite><?php echo $this->blogGroupPost['username'] ;?></cite> ::
            <abbr class="published">Published &nbsp;<?php echo $this->blogGroupPost['create_date']; ?></abbr>
        </p>


        <div class='meta'>
            <p>

                <?php echo $this->blogGroupPost['description']; ?>

            </p>

        </div>
    </div>

    <div>
        <p>         <a href="/admin/blog-groups/blog-group-post-publish-status/id/<?php echo $this->blogGroupPost['blog_group_post_id'] ?>" <?php echo ($this->blogGroupPost['blog_group_post_is_published'] == 0) ? "class='btn btn-success'": "class='btn btn-warning'" ?>><?php echo ($this->blogGroupPost['blog_group_post_is_published'] == 0) ? "Publish": "Unpublish" ?></a>
                    <a href="/admin/blog-groups/edit-blog-group-post/id/<?php echo $this->blogGroupPost['blog_group_post_id'] ?>" class="btn btn-success">Edit</a> &nbsp;&nbsp;
                    <a href="/admin/blog-groups/delete-blog-group-post/id/<?php echo $this->blogGroupPost['blog_group_post_id'] ?>" class="btn btn-danger">Delete</a></p>
    </div>

</div>
<?php }else{ ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
