<div class="row-fluid">
<div class="span12">
<h7>Write Comment Here : </h7>
</div>
</div>

<div class="well1">
<div class="row-fluid">
    <div class="span12">
        <?php if (empty($this->errorMsg)) : echo $this->flashMessenger(); ?>
        <?php else: ?>
   <div class="message errormsg"><p><?php echo $this->errorMsg ?></p></div>
        <?php endif; ?>
        <?php echo $this->commentForm; ?>
    </div>
</div>
</div>
