<div class="row-fluid">
    <h1>My Episode Draft </h1>


</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">

        <thead>
        <tr>
            <th width="5%">Serial</th>
            <th width="10%">Episode Name</th>
            <th width="30%">Discription</th>
            <th></th>
        </tr>
        </thead>

        <tbody>

        <?php if (!empty($this->getDraft)) : ?>

        <tr>
            <td colspan="7" class="report-no-data">No draft has been found.</td>
        </tr>

            <?php else: $count = 0;
            foreach ($this->Display AS $draft) : ?>

            <tr>
                <td class="centered"><?php echo ++$count ?></td>
                <td class="centered"><?php echo $draft['episode_number'] ?></td>
                <td class="centered"><?php echo $draft['description'] ?></td>

                <td class="centered">

                    <a class="btn " href="/blog/episods/edit/id/<?php echo $draft['blog_id'] ?>">Edit</a>
                    <a class="btn btn-warning" href="/user/draft/trash/id/<?php echo $draft['blog_id'] ?>">Trash</a>
                </td>
            </tr>
                <?php endforeach; endif ?>

        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


