<div class="row-fluid">
    <h1>My Episode Trash </h1>

   
</div>

<div class="row-fluid">

    <table id="draft-exams" class="zebra-striped bordered-table" style="margin-top: 20px">

        <thead>
            <tr>
                <th width="5%">Serial</th>
                <th width="10%">title</th>
                <th width="40%">Description</th>
                
             
            </tr>
        </thead>

        <tbody>

            <?php if (empty($this->Displaytrash)) : ?>

            <tr><td colspan="7" class="report-no-data">No Trash for Discussion.</td></tr>

            <?php else: $count = 0; foreach($this->Displaytrash AS $TrashEpisode) : ?>

            <tr>
                <td class="centered"><?php echo ++$count ?></td>
                <td class="centered"><?php echo $TrashEpisode['title'] ?></td>
				<td class="centered"><?php echo $TrashEpisode['description'] ?></td>
                
                <td class="centered">
                     <a class="btn btn-warning" href="/blog/episodes/trash/id/<?php echo $TrashEpisode['blog_id'] ?>">Restore</a>
                    <a class="btn danger delete" href="/user/draft/delete/id/<?php echo $TrashEpisode['blog_id'] ?>">Delete</a>
                </td>
            </tr>
            <?php endforeach; endif ?>

        </tbody>

    </table>

</div>

<div id="user-modal" class="modal hide fade"></div>


