<div class="row-fluid content-header">
    <br>
    <center>
        <h9>Episode</h9>
    </center>
    <?php
    $authNamespace = new Zend_Session_Namespace('userInformation');
    $authNamespace->userData['user_id'];
    ?>


</div>
<br/>


<div class="row-fluid">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Serial</th>
            <th>Episode Title</th>


        </tr>
        </thead>
        <tbody>

        <?php if (!empty($this->getAll)) : ?>

        <tr>
            <td></td>
            <td class="report-no-data" colspan="5">No episode has been found.</td>
            <td></td>
        </tr>

            <?php else: $count = 0;
            foreach ($this->display AS $display) : ?>

            <tr>
                <td><?php echo ++$count ?></td>
                <td><a
                    href="/episode-detail/<?php echo  $display['episode_id'] ?>"><?php echo $display['episode_name'] ?></a>
                </td>

            </tr>

                <?php endforeach; endif ?>


        </tbody>

    </table>
</div>
