<div class="row-fluid">
    <div class="span8">
        <h7>My Episode :</h7>
        <hr/>
        <?php
        $authNamespace = new Zend_Session_Namespace('userInformation');
        if (($authNamespace->userData['username']) == $this->userDetail['username']) {
            ?>
            <div style="float:right;">

                <a class="btn btn-success" href="/<?php echo $this->userDetail['username'] ?>/new-episode">Create New


                    Episode</a>

            </div>
            <?php } ?>



        <div class="tooltip-demo well1">
            <br>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Serial</th>
                    <th>Episode Title</th>
                    <th></th>

                </tr>
                </thead>
                <tbody>

                <?php if (empty($this->episode)) : ?>

                <tr>
                    <td></td>
                    <td class="report-no-data" colspan="5">No episode has been found.</td>
                    <td></td>
                </tr>

                    <?php else: $count = 0;
                    foreach ($this->episode AS $episode) : ?>

                    <tr>
                        <td><?php echo ++$count ?></td>
                        <td><a
                            href="/<?php echo $this->userDetail['username'] ?>/show-episodes/<?php echo  $episode['episode_id'] ?>"><?php echo $episode['episode_name'] ?></a>
                        </td>
                        <?php $cdata = $episode['create_by'];
                        if ($authNamespace->userData['user_id'] == $cdata) {
                            ?>
                            <td><a href="/blog/episodes/add/id/<?php echo  $episode['episode_id'] ?>">Continue
                                Writing</a></td>
                            <?php
                        }

                        ?>
                    </tr>

                        <?php endforeach; endif ?>


                </tbody>


            </table>
        </div>


    </div>

    <!--/right contain -->

    <div class="span4">
        <br><br>

        &nbsp;&nbsp;

        <h9> All Episode</h9>
        &nbsp;&nbsp;&nbsp;&nbsp;<img src="/public/../img/glyphicons_042_group.png">
        <hr/>

        <?php if (!empty($this->allEpisode)) : ?>
        <?php foreach ($this->allEpisode AS $allEpisode) : ?>


            <a href="/<?php echo $this->userDetail['username'] ?>/episode/<?php echo  $allEpisode['episode_id'] ?>"><?php echo $allEpisode['episode_name'] ?></a>


            <hr/>
            <?php endforeach; endif ?>

        &nbsp;&nbsp;
        <h9>আমার পছন্দের Episode</h9>
        <img src="/public/../img/glyphicons_042_group.png">
        <hr/>
        <a href="#">&nbsp;&nbsp;গডফাদার-৭৯</a>
        <hr/>
        <a href="#">&nbsp;&nbsp;আমার মুক্তি যুদ্ধ(ছোটদের জন্য) </a>
        <hr/>
        <a href="#">&nbsp;&nbsp;শ্রাবণ বাদলে</a>
        <hr/>
        <a href="#">&nbsp;&nbsp;কাঁচের ছবি-২ </a>
        <hr/>


        <!--/end right contain -->
    </div>

</div>



