<?php
$authNamespace = new Zend_Session_Namespace('userInformation');
$data          = $authNamespace->userData['user_id'];

?>

<?php if (!empty($this->episode)) { ?>

<div class="row-fluid content-header">
    <h7>Episode :</h7>
</div>
<hr/>
<div class="well1">

    Create by: <?php echo $this->episode['name']; ?><br>
    Episode Name: <?php echo $this->episode['episode_name']; ?><br>
    Episode Number: <?php echo $this->episode['episode_number']; ?><br>
    Description: <?php echo $this->episode['description']; ?>


</div>

<div class="well1">
    <table>


        <?php $cdata = $this->episode['create_by'];
        if ($data == $cdata) {
            ?>
            <tr>
                <td>
                    <?php if (!empty($this->episode)) { ?>
                    <a href="/<?php echo $this->userDetail['username'] ?>/episode-edit/<?php echo  $this->episode['blog_id'] ?>/<?php echo $this->episode['permalink'] ?>"
                       class="btn edit">Edit</a>
                    <?php
                }

                    ?>
                    <a href="/episode/delete/<?php echo $this->episode['blog_id'] ?>/<?php echo $this->episode['permalink'] ?>"
                       class="btn btn-danger">Delete</a>


                </td>

            </tr>
            <?php
        }

        ?>

        <tr>
            <td>
                <br>
                <a href="/episode-list/<?php echo $this->userDetail['username'] ?>" class="btn edit">Cancel</a>


            </td>
        </tr>

    </table>


</div>

<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>
