<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
        <li><a href="/admin/post-types">Post Types</a></li>
        <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
    </ul>
</div>
<br/><br/>
<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>
<?php if (!empty($this->display)) { ?>


<div class="span12">

    <div id="article-<?php echo $this->display['comment_id']; ?>">
        <h3><?php echo $this->display['description']; ?></h3>


        <div class='meta'>
            <h4 class='page-header'>Comments:
            </h4>

            <?php echo $this->display['comments']; ?>


            <?php
            if (!empty ($authNamespace->adminData['username'])): ?>
                <p>
                    <a href="/admin/comments/publish/id/<?php echo $this->display['comment_id'] ?>" <?php echo ($this->display['is_published'] == 0) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->display['is_published'] == 0) ? "Publish" : "Unpublish" ?></a>

                    <a href="/admin/blogs/sticky/id/<?php echo $this->display['comment_id'] ?>" <?php echo ($this->blog['sticky_on_home_page'] == 0) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->blog['sticky_on_home_page'] == 0) ? "Sticky" : "Cancel sticky" ?></a>
                    <a href="/admin/comments/edit/id/<?php echo  $this->display['comment_id'] ?>"
                       class="btn edit">Edit</a>
                    <a href="/admin/comments/delete/id/<?php echo $this->display['comment_id'] ?>"
                       class="btn btn-danger">Delete</a>
                </p>
                <?php endif ?>

        </div>
    </div>
</div>
<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>

