<div class="subnav">
    <ul class="nav nav-pills">
        <li><a href="/admin/blogs/index">All Blogs</a></li>
        <li><a href="/admin/categories">Category</a></li>
        <li><a href="/admin/post-types">Post Types</a></li>
        <li><a href="/admin/blog-group-types">Blog Group Types</a></li>
        <li><a href="/admin/blog-groups">Blog Groups</a></li>
        <li><a href="/admin/comments">Comments</a></li>
    </ul>
</div>
<br/><br/>
<?php $authNamespace = new Zend_Session_Namespace('adminInformation'); ?>
<?php if (!empty($this->display)) { ?>

<div class="span12">

    <div id="article-<?php echo $this->display['comment_id']; ?>">
        <h3><?php echo $this->display['title']; ?></h3>
        <hr/>
        <p>
            <?php echo $this->display['description']; ?>
        </p>


        <div class='meta'>
            <p>Comments: </p>
            <?php echo $this->display['comments']; ?>

        <p>
            <?php
            if (!empty ($authNamespace->adminData['username'])): ?>
                <p>
                    <a href="/admin/comments/publish/id/<?php echo $this->display['comment_id'] ?>" <?php echo ($this->display['is_published'] == 1) ? "class='btn btn-success'" : "class='btn btn-warning'" ?>><?php echo ($this->display['is_published'] == 1) ? "Publish" : "Unpublish" ?></a>


                    <a href="/admin/comments/edit/id/<?php echo  $this->display['comment_id'] ?>"
                       class="btn edit">Edit</a>
                    <a href="/admin/comments/delete/id/<?php echo $this->display['comment_id'] ?>"
                       class="btn btn-danger">Delete</a>
                </p>
                <?php endif ?>
            </p>

        </div>
    </div>
</div>
<?php } else { ?>

<div class="span6">
    <h3>No such post to show</h3>
</div>
<?php } ?>

